# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileLifeCycleSettings")

model_instance <- FileLifeCycleSettings$new()

test_that("timeGracePeriodEnds", {
  # tests for the property `timeGracePeriodEnds` (character)
  # If set, date when billing for the file will start

  # uncomment below to test the property
  #expect_equal(model.instance$`timeGracePeriodEnds`, "EXPECTED_RESULT")
})

test_that("timeToBeArchived", {
  # tests for the property `timeToBeArchived` (character)
  # If set, date when file will be archived

  # uncomment below to test the property
  #expect_equal(model.instance$`timeToBeArchived`, "EXPECTED_RESULT")
})

test_that("timeToBeDeleted", {
  # tests for the property `timeToBeDeleted` (character)
  # If set, date when file will be deleted

  # uncomment below to test the property
  #expect_equal(model.instance$`timeToBeDeleted`, "EXPECTED_RESULT")
})

test_that("archiveStorageTier", {
  # tests for the property `archiveStorageTier` (FileArchiveStorageTier)

  # uncomment below to test the property
  #expect_equal(model.instance$`archiveStorageTier`, "EXPECTED_RESULT")
})
