# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AwsS3TemporaryUploadCredentials")

model_instance <- AwsS3TemporaryUploadCredentials$new()

test_that("access_Key_Id", {
  # tests for the property `access_Key_Id` (character)
  # Access key for use with AWS S3

  # uncomment below to test the property
  #expect_equal(model.instance$`access_Key_Id`, "EXPECTED_RESULT")
})

test_that("secret_Access_Key", {
  # tests for the property `secret_Access_Key` (character)
  # Secret key for use with AWS S3

  # uncomment below to test the property
  #expect_equal(model.instance$`secret_Access_Key`, "EXPECTED_RESULT")
})

test_that("session_Token", {
  # tests for the property `session_Token` (character)
  # Token for use with AWS S3

  # uncomment below to test the property
  #expect_equal(model.instance$`session_Token`, "EXPECTED_RESULT")
})

test_that("region", {
  # tests for the property `region` (character)
  # AWS region the folder will/does reside in

  # uncomment below to test the property
  #expect_equal(model.instance$`region`, "EXPECTED_RESULT")
})

test_that("bucketName", {
  # tests for the property `bucketName` (character)
  # AWS bucket the folder will/does reside in

  # uncomment below to test the property
  #expect_equal(model.instance$`bucketName`, "EXPECTED_RESULT")
})

test_that("keyPrefix", {
  # tests for the property `keyPrefix` (character)
  # AWS upload location for this folder

  # uncomment below to test the property
  #expect_equal(model.instance$`keyPrefix`, "EXPECTED_RESULT")
})

test_that("expirationDate", {
  # tests for the property `expirationDate` (character)
  # expiration for temporary credentials

  # uncomment below to test the property
  #expect_equal(model.instance$`expirationDate`, "EXPECTED_RESULT")
})

test_that("serviceUrl", {
  # tests for the property `serviceUrl` (character)
  # Service endpoint for accessing S3.  This is optional for AWS S3, but mandatory for other services like Taiwan Computing Cloud.

  # uncomment below to test the property
  #expect_equal(model.instance$`serviceUrl`, "EXPECTED_RESULT")
})

test_that("serverSideEncryptionAlgorithm", {
  # tests for the property `serverSideEncryptionAlgorithm` (character)
  # Used to specify the type of server-side encryption (SSE) to be used on the object provider.  This value is used to determine the Amazon S3 header \&quot;x-amz-server-side-encryption\&quot; value.  For example, specify \&quot;AES256\&quot; for SSE-S3, or \&quot;AWS:KMS\&quot; for SSE-KMS.  By default if none is specified, \&quot;AES256\&quot; will be used.

  # uncomment below to test the property
  #expect_equal(model.instance$`serverSideEncryptionAlgorithm`, "EXPECTED_RESULT")
})

test_that("serverSideEncryptionKey", {
  # tests for the property `serverSideEncryptionKey` (character)
  # Used to specify the serve-side encryption key that might be associated with the specified server-side encryption algorithm  This value can be the AWS KMS arn key, to be used for the Amazon S3 header \&quot;x-amz-server-side-encryption-aws-kms-key-id\&quot; value  Value will be ignored if encryption is \&quot;AES256\&quot;

  # uncomment below to test the property
  #expect_equal(model.instance$`serverSideEncryptionKey`, "EXPECTED_RESULT")
})
