# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkFolderUpdateRequest")

model_instance <- BulkFolderUpdateRequest$new()

test_that("items", {
  # tests for the property `items` (array[BulkFolderUpdateItem])

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("timeOutInSeconds", {
  # tests for the property `timeOutInSeconds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`timeOutInSeconds`, "EXPECTED_RESULT")
})
