# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateVolumeRequest")

model_instance <- UpdateVolumeRequest$new()

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this volume and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("lifeCycle", {
  # tests for the property `lifeCycle` (VolumeLifeCycleSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`lifeCycle`, "EXPECTED_RESULT")
})
