# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateFolderRequest")

model_instance <- CreateFolderRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # Folder name, unique to this path, for the folder being created

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("folderPath", {
  # tests for the property `folderPath` (character)
  # Path from the root folder to the location for the folder being created; must start and end with &#39;/&#39;

  # uncomment below to test the property
  #expect_equal(model.instance$`folderPath`, "EXPECTED_RESULT")
})

test_that("volumeId", {
  # tests for the property `volumeId` (character)
  # The unique identifier for this Folder&#39;s Volume

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})

test_that("volumeName", {
  # tests for the property `volumeName` (character)
  # The unique name for the Folder&#39;s Volume

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeName`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this folder and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Optional array to replace the acl on the resource.

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})
