# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateWorkflowRequest")

model_instance <- UpdateWorkflowRequest$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("organization", {
  # tests for the property `organization` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organization`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("categories", {
  # tests for the property `categories` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`categories`, "EXPECTED_RESULT")
})
