# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkMetadataUpdateOperationParameters")

model_instance <- BulkMetadataUpdateOperationParameters$new()

test_that("folderId", {
  # tests for the property `folderId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderId`, "EXPECTED_RESULT")
})

test_that("folderPath", {
  # tests for the property `folderPath` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderPath`, "EXPECTED_RESULT")
})

test_that("volumeId", {
  # tests for the property `volumeId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})

test_that("fileStatus", {
  # tests for the property `fileStatus` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileStatus`, "EXPECTED_RESULT")
})

test_that("parentFolderMetadataUpdates", {
  # tests for the property `parentFolderMetadataUpdates` (MetadataUpdateRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentFolderMetadataUpdates`, "EXPECTED_RESULT")
})

test_that("childrenFoldersUpdates", {
  # tests for the property `childrenFoldersUpdates` (MetadataUpdateRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`childrenFoldersUpdates`, "EXPECTED_RESULT")
})

test_that("childrenFilesUpdates", {
  # tests for the property `childrenFilesUpdates` (MetadataUpdateRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`childrenFilesUpdates`, "EXPECTED_RESULT")
})
