# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HeartbeatTaskRunRequest")

model_instance <- HeartbeatTaskRunRequest$new()

test_that("lastHeartbeat", {
  # tests for the property `lastHeartbeat` (character)
  # LastHeartbeat

  # uncomment below to test the property
  #expect_equal(model.instance$`lastHeartbeat`, "EXPECTED_RESULT")
})

test_that("podName", {
  # tests for the property `podName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`podName`, "EXPECTED_RESULT")
})

test_that("podUID", {
  # tests for the property `podUID` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`podUID`, "EXPECTED_RESULT")
})

test_that("podHardwareDetails", {
  # tests for the property `podHardwareDetails` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`podHardwareDetails`, "EXPECTED_RESULT")
})

test_that("jobRetryCount", {
  # tests for the property `jobRetryCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`jobRetryCount`, "EXPECTED_RESULT")
})

test_that("nonce", {
  # tests for the property `nonce` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nonce`, "EXPECTED_RESULT")
})

test_that("containerStatus", {
  # tests for the property `containerStatus` (array[ContainerStatus])

  # uncomment below to test the property
  #expect_equal(model.instance$`containerStatus`, "EXPECTED_RESULT")
})
