# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeliveryTarget")

model_instance <- DeliveryTarget$new()

test_that("awsSnsTopic", {
  # tests for the property `awsSnsTopic` (DeliveryTargetAwsSnsTopic)

  # uncomment below to test the property
  #expect_equal(model.instance$`awsSnsTopic`, "EXPECTED_RESULT")
})

test_that("awsSqsQueue", {
  # tests for the property `awsSqsQueue` (DeliveryTargetAwsSqsQueue)

  # uncomment below to test the property
  #expect_equal(model.instance$`awsSqsQueue`, "EXPECTED_RESULT")
})

test_that("workflowRunLaunch", {
  # tests for the property `workflowRunLaunch` (DeliveryTargetWorkflowRunLaunch)

  # uncomment below to test the property
  #expect_equal(model.instance$`workflowRunLaunch`, "EXPECTED_RESULT")
})
