# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilesApi")

api_instance <- FilesApi$new()

test_that("ArchiveFile", {
  # tests for ArchiveFile
  # base path: http://aps2.platform.illumina.com
  # Archive a file
  # Archives a file to a lower storage cost tier.
  # @param file_id character Unique identifier for the file to be archived.
  # @param body FileArchiveRequest 
  # @return [FileResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BulkFileUpdate", {
  # tests for BulkFileUpdate
  # base path: http://aps2.platform.illumina.com
  # Updates list of files with metadata
  # Updates list of files with metadata
  # @param body BulkFileUpdateRequest  (optional)
  # @return [BulkFileUpdateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CompleteFileUpload", {
  # tests for CompleteFileUpload
  # base path: http://aps2.platform.illumina.com
  # Complete a file Upload
  # Complete a file upload operation. If the file was uploaded using multipart uploads, combine all the multiple parts uploaded into one complete file.
  # @param file_id character Unique identifier for the file upload to be completed.
  # @param body FileUploadCompleteRequest 
  # @return [FileResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CopyFiles", {
  # tests for CopyFiles
  # base path: http://aps2.platform.illumina.com
  # Copy list of files
  # Copies a list of files enumerated by file Ids to a destination folder
  # @param body FileListCopyRequest 
  # @return [JobResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateFile", {
  # tests for CreateFile
  # base path: http://aps2.platform.illumina.com
  # Create a file entry in GDS and get temporary credentials for upload
  # Create a file entry in GDS. Returns temporary credentials and presigned url(s) for file upload directly to S3 when the include&#x3D;objectStoreAccess parameter is used. Volume ID or volume name is required for file creation. If a folder path is provided and does not exist, GDS creates the folder path in the appropriate account automatically.
  # @param body CreateFileRequest 
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @param upload_part_count integer Optional number of parts for the presigned url for uploads (1 - 10000) (optional)
  # @return [FileWriteableResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteFile", {
  # tests for DeleteFile
  # base path: http://aps2.platform.illumina.com
  # Permanently delete a file
  # Permanently delete a file entry and its underlying content
  # @param file_id character Unique identifier for the file to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFile", {
  # tests for GetFile
  # base path: http://aps2.platform.illumina.com
  # Get details about a file, including a pre-signed URL for download
  # Get information and details for the specified file ID, including metadata and a pre-signed URL for file download. The URL can be used as a curl command or directly with S3.
  # @param file_id character Unique identifier for the file to retrieve.
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param presigned_url_mode character Optional parameter to specify presigned url's content-disposition. If not specified, the browser will determine the default behavior.              Possible values: Attachment, Inline, Browser (optional)
  # @param include_volume_metadata character Optional parameter to return volume's metadata (optional)
  # @param metadata_include character Optional parameter to specify comma separated patterns to include metadata by their field names. (optional)
  # @param metadata_exclude character Optional parameter to specify comma separated patterns to exclude metadata by their field names. (optional)
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @return [FileResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListFiles", {
  # tests for ListFiles
  # base path: http://aps2.platform.illumina.com
  # Get a list of files
  # Given a volumeId or volume name, get a list of files accessible by the JWT. The default sort returned is alphabetical, ascending. The default page size is 10 items
  # @param volume_id array[character] Optional field that specifies comma-separated volume IDs to include in the list (optional)
  # @param volume_name array[character] Optional field that specifies comma-separated volume names to include in the list (optional)
  # @param path array[character] Optional field that specifies comma-separated paths to include in the list. Value can use wildcards (e.g. /a/b/c/*) or exact matches (e.g. /a/b/c/d/). (optional)
  # @param is_uploaded character Optional field to filter by Uploaded files (optional)
  # @param archive_status character Optional field that specifies comma-separated Archive Statuses to include in the list (optional)
  # @param recursive character Optional field to specify if files should be returned recursively in and under the specified paths, or only directly in the specified paths (optional)
  # @param presigned_url_mode character Optional parameter to specify presigned url's content-disposition. If not specified, the browser will determine the default behavior.  Possible values: Attachment, Inline, Browser (optional)
  # @param include character Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, PresignedUrl, InheritedAcl (optional)
  # @param page_size integer START_DESC END_DESC (optional)
  # @param page_token character START_DESC END_DESC (optional)
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param metadata_include character Optional parameter to specify comma separated patterns to include metadata by their field names. (optional)
  # @param metadata_exclude character Optional parameter to specify comma separated patterns to exclude metadata by their field names. (optional)
  # @return [FileListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListVolumeFiles", {
  # tests for ListVolumeFiles
  # base path: http://aps2.platform.illumina.com
  # Get a list of volume files
  # Gets file list by volume ID and an array of file IDs. The default sort returned is alphabetical, ascending
  # @param body VolumeFileListRequest 
  # @return [VolumeFileListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UnarchiveFile", {
  # tests for UnarchiveFile
  # base path: http://aps2.platform.illumina.com
  # Unarchive a file
  # Unarchive a file from a lower storage cost tier.
  # @param file_id character Unique identifier for the file to be unarchived.
  # @param body FileUnarchiveRequest 
  # @return [FileResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateFile", {
  # tests for UpdateFile
  # base path: http://aps2.platform.illumina.com
  # Update a file entry in GDS and get temporary credentials for upload
  # Update a file entry in GDS. Returns temporary credentials and presigned url(s) for file upload directly to S3 when the include&#x3D;objectStoreAccess parameter is used. Note that the currently supported changes to the file resource are updating the file type and the underlying content.
  # @param file_id character Unique identifier for the file to be updated.
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @param upload_part_count integer Optional number of parts for the presigned url for uploads (1 - 10000) (optional)
  # @param body UpdateFileRequest  (optional)
  # @return [FileWriteableResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
