# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContainerState")

model_instance <- ContainerState$new()

test_that("waiting", {
  # tests for the property `waiting` (ContainerStateWaiting)

  # uncomment below to test the property
  #expect_equal(model.instance$`waiting`, "EXPECTED_RESULT")
})

test_that("running", {
  # tests for the property `running` (ContainerStateRunning)

  # uncomment below to test the property
  #expect_equal(model.instance$`running`, "EXPECTED_RESULT")
})

test_that("terminated", {
  # tests for the property `terminated` (ContainerStateTerminated)

  # uncomment below to test the property
  #expect_equal(model.instance$`terminated`, "EXPECTED_RESULT")
})
