# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VolumeConfigurationsApi")

api_instance <- VolumeConfigurationsApi$new()

test_that("CreateVolumeConfiguration", {
  # tests for CreateVolumeConfiguration
  # base path: http://aps2.platform.illumina.com
  # Create a volume configuration in GDS.
  # Create a volume configuration in GDS. This contains the object store details that will be used to create volumes.
  # @param body CreateVolumeConfigurationRequest 
  # @return [VolumeConfigurationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteVolumeConfiguration", {
  # tests for DeleteVolumeConfiguration
  # base path: http://aps2.platform.illumina.com
  # Deletes a volume configuration by Id or name
  # @param volume_configuration_name character Unique name of the Volume Configuration to be deleted.
  # @return [VolumeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetVolumeConfiguration", {
  # tests for GetVolumeConfiguration
  # base path: http://aps2.platform.illumina.com
  # Get information for the specified volume configuration name or Id
  # @param volume_configuration_name character Unique name of the volume configuration to retrieve information for.
  # @return [VolumeConfigurationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListVolumeConfigurations", {
  # tests for ListVolumeConfigurations
  # base path: http://aps2.platform.illumina.com
  # Get a list of volumes
  # @param online_status character Optional field that specifies the Online Status for Volume configurations included in the list.  If provided, the value must be Initializing, Ok, or Error. (optional)
  # @param page_size integer START_DESC END_DESC (optional)
  # @param page_token character START_DESC END_DESC (optional)
  # @param include character Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl (optional)
  # @return [VolumeConfigurationListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ValidateVolumeConfiguration", {
  # tests for ValidateVolumeConfiguration
  # base path: http://aps2.platform.illumina.com
  # Validate a volume configuration
  # Validate an existing volume configuration.
  # @param volume_configuration_name character Unique name of the volume configuration to be validated.
  # @return [VolumeConfigurationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
