# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FailWorkflowSignalRequest")

model_instance <- FailWorkflowSignalRequest$new()

test_that("error", {
  # tests for the property `error` (character)
  # Externally provided Error of a signalling action.

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("cause", {
  # tests for the property `cause` (character)
  # Externally provided Cause of a failed signalling action.

  # uncomment below to test the property
  #expect_equal(model.instance$`cause`, "EXPECTED_RESULT")
})
