# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobOutput")

model_instance <- JobOutput$new()

test_that("folderCopy", {
  # tests for the property `folderCopy` (FileCopyOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderCopy`, "EXPECTED_RESULT")
})

test_that("fileCopy", {
  # tests for the property `fileCopy` (FileCopyOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileCopy`, "EXPECTED_RESULT")
})

test_that("folderMetadataUpdateOutput", {
  # tests for the property `folderMetadataUpdateOutput` (MetadataUpdateOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderMetadataUpdateOutput`, "EXPECTED_RESULT")
})

test_that("fileMetadataUpdateOutput", {
  # tests for the property `fileMetadataUpdateOutput` (MetadataUpdateOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileMetadataUpdateOutput`, "EXPECTED_RESULT")
})
