# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Environment")

model_instance <- Environment$new()

test_that("variables", {
  # tests for the property `variables` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`variables`, "EXPECTED_RESULT")
})

test_that("resources", {
  # tests for the property `resources` (Resources)

  # uncomment below to test the property
  #expect_equal(model.instance$`resources`, "EXPECTED_RESULT")
})

test_that("inputStreamSettings", {
  # tests for the property `inputStreamSettings` (InputStreamSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`inputStreamSettings`, "EXPECTED_RESULT")
})
