# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SucceedWorkflowSignalRequest")

model_instance <- SucceedWorkflowSignalRequest$new()

test_that("result", {
  # tests for the property `result` (object)
  # External result of a successful signal. Must resolve to a JSON value.

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})
