# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Resources")

model_instance <- Resources$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("cpuCores", {
  # tests for the property `cpuCores` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`cpuCores`, "EXPECTED_RESULT")
})

test_that("memoryGb", {
  # tests for the property `memoryGb` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`memoryGb`, "EXPECTED_RESULT")
})

test_that("hardware", {
  # tests for the property `hardware` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`hardware`, "EXPECTED_RESULT")
})

test_that("tier", {
  # tests for the property `tier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tier`, "EXPECTED_RESULT")
})
