# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartInfo")

model_instance <- PartInfo$new()

test_that("part", {
  # tests for the property `part` (integer)
  # Part number to be applied to {part} in MultipartTemplate

  # uncomment below to test the property
  #expect_equal(model.instance$`part`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)
  # Date to be applied to {date} in MultipartTemplate

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("dateTime", {
  # tests for the property `dateTime` (character)
  # DateTime to be applied to {datetime} in MultipartTemplate

  # uncomment below to test the property
  #expect_equal(model.instance$`dateTime`, "EXPECTED_RESULT")
})

test_that("signature", {
  # tests for the property `signature` (character)
  # Signature to be applied to {signature} in MultipartTemplate

  # uncomment below to test the property
  #expect_equal(model.instance$`signature`, "EXPECTED_RESULT")
})
