# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CheckOutQueuedTaskRunRequest")

model_instance <- CheckOutQueuedTaskRunRequest$new()

test_that("computeType", {
  # tests for the property `computeType` (character)
  # Type of the compute requested (Fpga and NonFpga)

  # uncomment below to test the property
  #expect_equal(model.instance$`computeType`, "EXPECTED_RESULT")
})
