# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VolumeFileListResponse")

model_instance <- VolumeFileListResponse$new()

test_that("items", {
  # tests for the property `items` (array[FileResponse])
  # Retrieved files

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("itemSuccessCount", {
  # tests for the property `itemSuccessCount` (integer)
  # Number of items that succeeded

  # uncomment below to test the property
  #expect_equal(model.instance$`itemSuccessCount`, "EXPECTED_RESULT")
})

test_that("itemFailedCount", {
  # tests for the property `itemFailedCount` (integer)
  # Number of items that failed

  # uncomment below to test the property
  #expect_equal(model.instance$`itemFailedCount`, "EXPECTED_RESULT")
})

test_that("itemsFailed", {
  # tests for the property `itemsFailed` (array[BulkFailedItem])
  # Item failures with error details

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsFailed`, "EXPECTED_RESULT")
})
