# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateTaskVersionRequest")

model_instance <- CreateTaskVersionRequest$new()

test_that("version", {
  # tests for the property `version` (character)
  # User-defined version of task version

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # User-defined description of task version

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("execution", {
  # tests for the property `execution` (Execution)

  # uncomment below to test the property
  #expect_equal(model.instance$`execution`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})
