# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileUnarchiveRequest")

model_instance <- FileUnarchiveRequest$new()

test_that("restoreSpeed", {
  # tests for the property `restoreSpeed` (character)
  # The desired Restore Speed to move the File to the Standard Storage Tier. Valid values are Economy and Standard.

  # uncomment below to test the property
  #expect_equal(model.instance$`restoreSpeed`, "EXPECTED_RESULT")
})
