# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkFolderUpdateResponse")

model_instance <- BulkFolderUpdateResponse$new()

test_that("itemsFailed", {
  # tests for the property `itemsFailed` (array[BulkUpdateFailedItem])
  # Items failed to be updated with error details

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsFailed`, "EXPECTED_RESULT")
})

test_that("itemsUpdatedCount", {
  # tests for the property `itemsUpdatedCount` (integer)
  # Total items successfully updated

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsUpdatedCount`, "EXPECTED_RESULT")
})

test_that("itemsFailedCount", {
  # tests for the property `itemsFailedCount` (integer)
  # Total items failed to be updated

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsFailedCount`, "EXPECTED_RESULT")
})
