# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateFileRequest")

model_instance <- UpdateFileRequest$new()

test_that("type", {
  # tests for the property `type` (character)
  # The new file type (e.g. \&quot;text/plain\&quot;).

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)
  # The File&#39;s Format

  # uncomment below to test the property
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

test_that("formatEdam", {
  # tests for the property `formatEdam` (character)
  # The File&#39;s Edam Format

  # uncomment below to test the property
  #expect_equal(model.instance$`formatEdam`, "EXPECTED_RESULT")
})

test_that("lifeCycle", {
  # tests for the property `lifeCycle` (FileLifeCycleSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`lifeCycle`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this file and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})
