# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateClusterRequest")

model_instance <- UpdateClusterRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # User-defined name of the cluster

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("svcAcctUId", {
  # tests for the property `svcAcctUId` (character)
  # Service account user id to be associated with the cluster

  # uncomment below to test the property
  #expect_equal(model.instance$`svcAcctUId`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # User-defined status of the cluster

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # User-defined type of the cluster

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Access Control List

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})
