# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeliveryTargetWorkflowRunLaunch")

model_instance <- DeliveryTargetWorkflowRunLaunch$new()

test_that("id", {
  # tests for the property `id` (character)
  # Id of the workflow to launch

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Version of the workflow to launch, for the given id

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name for the workflowRun

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("input", {
  # tests for the property `input` (object)
  # Arguments for the workflowRun

  # uncomment below to test the property
  #expect_equal(model.instance$`input`, "EXPECTED_RESULT")
})
