# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Image")

model_instance <- Image$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name of url for Docker Image

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)
  # Version of image as defined in repository

  # uncomment below to test the property
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})

test_that("digest", {
  # tests for the property `digest` (character)
  # Version of image as defined in repository

  # uncomment below to test the property
  #expect_equal(model.instance$`digest`, "EXPECTED_RESULT")
})

test_that("credentials", {
  # tests for the property `credentials` (Credentials)

  # uncomment below to test the property
  #expect_equal(model.instance$`credentials`, "EXPECTED_RESULT")
})
