# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SystemFiles")

model_instance <- SystemFiles$new()

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("storageProvider", {
  # tests for the property `storageProvider` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageProvider`, "EXPECTED_RESULT")
})

test_that("credentials", {
  # tests for the property `credentials` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`credentials`, "EXPECTED_RESULT")
})
