# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AbortWorkflowRunRequest")

model_instance <- AbortWorkflowRunRequest$new()

test_that("error", {
  # tests for the property `error` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("cause", {
  # tests for the property `cause` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cause`, "EXPECTED_RESULT")
})
