# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileListCopyRequest")

model_instance <- FileListCopyRequest$new()

test_that("sourceVolumeId", {
  # tests for the property `sourceVolumeId` (character)
  # The volume where the source files are copied from.

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceVolumeId`, "EXPECTED_RESULT")
})

test_that("destinationFolderId", {
  # tests for the property `destinationFolderId` (character)
  # The folder into which the source folder will be copied.

  # uncomment below to test the property
  #expect_equal(model.instance$`destinationFolderId`, "EXPECTED_RESULT")
})

test_that("ids", {
  # tests for the property `ids` (array[character])
  # List of files ids to copy

  # uncomment below to test the property
  #expect_equal(model.instance$`ids`, "EXPECTED_RESULT")
})

test_that("metadataToCopy", {
  # tests for the property `metadataToCopy` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`metadataToCopy`, "EXPECTED_RESULT")
})

test_that("duplicateFileAction", {
  # tests for the property `duplicateFileAction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`duplicateFileAction`, "EXPECTED_RESULT")
})
