# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskVersionsApi")

api_instance <- TaskVersionsApi$new()

test_that("CreateTaskVersion", {
  # tests for CreateTaskVersion
  # base path: http://aps2.platform.illumina.com
  # Create a task version
  # Creates a new task version within an existing task. Returns the ID associated with the new task version. Substitutions can be defined in the following format: \&quot;{{string}}\&quot;, and specified at launch time.
  # @param task_id character 
  # @param body CreateTaskVersionRequest  (optional)
  # @return [TaskVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaskVersion", {
  # tests for GetTaskVersion
  # base path: http://aps2.platform.illumina.com
  # Get the details of a task version
  # Gets details of a task version for a given task version ID.
  # @param task_id character 
  # @param version_id character 
  # @return [TaskVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("LaunchTaskRun", {
  # tests for LaunchTaskRun
  # base path: http://aps2.platform.illumina.com
  # Launch a task version
  # Launches a task version for a given task version ID. Returns the ID associated with the new task run. Substitutions defined in the task version must be specified.
  # @param task_id character 
  # @param version_id character 
  # @param body LaunchTaskRequest  (optional)
  # @return [TaskRun]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTaskVersions", {
  # tests for ListTaskVersions
  # base path: http://aps2.platform.illumina.com
  # Get a list of versions
  # Gets a list of task versions within the given task accessible by the current tenant ID.
  # @param task_id character 
  # @param sort character Sort: Optional parameter to set the sort of the returned list. Valid fields include: name, version, timeCreated, timeModified.  The sort can be specified as asc or desc. (Default: asc.) (optional)
  # @param versions character  (optional)
  # @param ids character  (optional)
  # @param acls character  (optional)
  # @param page_size integer Optional parameter to define the page size returned. Valid inputs range from 1-1000. (optional)
  # @param page_token character pageToken: Optional parameter for navigation after initial listing. Valid values include firstPageToken,  nextPageToken, and previousPageToken (provided in the list response) (optional)
  # @return [TaskVersionSummaryPagedItems]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateTaskVersion", {
  # tests for UpdateTaskVersion
  # base path: http://aps2.platform.illumina.com
  # Update task version properties
  # Update details of a task version for a given task version ID.
  # @param task_id character 
  # @param version_id character 
  # @param body UpdateTaskVersionRequest  (optional)
  # @return [TaskVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
