# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskRunSummary")

model_instance <- TaskRunSummary$new()

test_that("id", {
  # tests for the property `id` (character)
  # Global identifier for object

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (character)
  # Href of the object

  # uncomment below to test the property
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)
  # URN of the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("statusDetails", {
  # tests for the property `statusDetails` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`statusDetails`, "EXPECTED_RESULT")
})

test_that("typeOfResource", {
  # tests for the property `typeOfResource` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`typeOfResource`, "EXPECTED_RESULT")
})

test_that("sizeOfResource", {
  # tests for the property `sizeOfResource` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sizeOfResource`, "EXPECTED_RESULT")
})

test_that("tierOfResource", {
  # tests for the property `tierOfResource` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tierOfResource`, "EXPECTED_RESULT")
})

test_that("taskVersionSummary", {
  # tests for the property `taskVersionSummary` (TaskVersionSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`taskVersionSummary`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Access Control List

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("subTenantId", {
  # tests for the property `subTenantId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subTenantId`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # User who created the object

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # Date and Time (in UTC) when object was created in TES

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # User who updated the object

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("timeModified", {
  # tests for the property `timeModified` (character)
  # Date and Time (in UTC) when object was modified in TES

  # uncomment below to test the property
  #expect_equal(model.instance$`timeModified`, "EXPECTED_RESULT")
})
