# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskRunsApi")

api_instance <- TaskRunsApi$new()

test_that("AbortTaskRun", {
  # tests for AbortTaskRun
  # base path: http://aps2.platform.illumina.com
  # Abort a task run
  # Aborts a task run for a given task run ID. The task run is required to have a status of \&quot;Pending\&quot; or \&quot;Running\&quot;.
  # @param run_id character 
  # @return [TaskRunSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateTaskRun", {
  # tests for CreateTaskRun
  # base path: http://aps2.platform.illumina.com
  # Create and launch a task run
  # Creates and launches a task run. Returns the ID and status associated with the new task run.
  # @param body CreateTaskRunRequest  (optional)
  # @return [TaskRun]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTaskRun", {
  # tests for GetTaskRun
  # base path: http://aps2.platform.illumina.com
  # Get the status of a task run
  # Gets the status of a task run for a given task run ID.
  # @param run_id character 
  # @return [TaskRun]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("HeartbeatTaskRun", {
  # tests for HeartbeatTaskRun
  # base path: http://aps2.platform.illumina.com
  # Heartbeat for a task run
  # Heartbeat a task run for a given task run ID. This notifies TES that a task run is executing.
  # @param run_id character 
  # @param body HeartbeatTaskRunRequest  (optional)
  # @return [TaskRunHeartbeat]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTaskRuns", {
  # tests for ListTaskRuns
  # base path: http://aps2.platform.illumina.com
  # Get a list of task runs
  # Get a list of task runs accessible by the current tenant ID.
  # @param sort character Sort: Optional parameter to set the sort of the returned list. Valid fields include: name, status, timeCreated, timeModified.  The sort can be specified as asc or desc. (Default: asc.) (optional)
  # @param names character  (optional)
  # @param status character  (optional)
  # @param versions character  (optional)
  # @param acls character  (optional)
  # @param page_size integer Optional parameter to define the page size returned. Valid inputs range from 1-1000. (optional)
  # @param page_token character pageToken: Optional parameter for navigation after initial listing. Valid values include firstPageToken,  nextPageToken, and previousPageToken (provided in the list response) (optional)
  # @return [TaskRunSummaryPagedItems]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
