# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkUpdateFailedItem")

model_instance <- BulkUpdateFailedItem$new()

test_that("id", {
  # tests for the property `id` (character)
  # Id of resource that failed to be updated

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("errorResponse", {
  # tests for the property `errorResponse` (ErrorResponse)

  # uncomment below to test the property
  #expect_equal(model.instance$`errorResponse`, "EXPECTED_RESULT")
})
