# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobOperationParameters")

model_instance <- JobOperationParameters$new()

test_that("folderCopy", {
  # tests for the property `folderCopy` (FolderCopyOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderCopy`, "EXPECTED_RESULT")
})

test_that("folderDelete", {
  # tests for the property `folderDelete` (FolderDeleteOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`folderDelete`, "EXPECTED_RESULT")
})

test_that("volumeMigration", {
  # tests for the property `volumeMigration` (VolumeMigrationOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeMigration`, "EXPECTED_RESULT")
})

test_that("fileCopy", {
  # tests for the property `fileCopy` (FileCopyOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileCopy`, "EXPECTED_RESULT")
})

test_that("bulkMetadataUpdate", {
  # tests for the property `bulkMetadataUpdate` (BulkMetadataUpdateOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`bulkMetadataUpdate`, "EXPECTED_RESULT")
})
