# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileArchiveRequest")

model_instance <- FileArchiveRequest$new()

test_that("storageTier", {
  # tests for the property `storageTier` (FileArchiveStorageTier)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageTier`, "EXPECTED_RESULT")
})
