# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateVolumeConfigurationRequest")

model_instance <- CreateVolumeConfigurationRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name for the volume configuration

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("versioningEnabled", {
  # tests for the property `versioningEnabled` (character)
  # Versioning Enabled or Suspended for the ObjectContainer

  # uncomment below to test the property
  #expect_equal(model.instance$`versioningEnabled`, "EXPECTED_RESULT")
})

test_that("objectStoreSettings", {
  # tests for the property `objectStoreSettings` (ObjectStoreSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectStoreSettings`, "EXPECTED_RESULT")
})

test_that("restoreType", {
  # tests for the property `restoreType` (RestoreType)

  # uncomment below to test the property
  #expect_equal(model.instance$`restoreType`, "EXPECTED_RESULT")
})
