# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContainerStatus")

model_instance <- ContainerStatus$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (ContainerState)

  # uncomment below to test the property
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})
