# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FolderCopyRequest")

model_instance <- FolderCopyRequest$new()

test_that("targetParentFolderId", {
  # tests for the property `targetParentFolderId` (character)
  # The parent folder into which the source folder will be copied.

  # uncomment below to test the property
  #expect_equal(model.instance$`targetParentFolderId`, "EXPECTED_RESULT")
})

test_that("destinationFolderName", {
  # tests for the property `destinationFolderName` (character)
  # A new name for the destination folder. Required if target parent folder is the same as the destination folder.  When optional and not provided, the source folder name is used as the destination folder name.

  # uncomment below to test the property
  #expect_equal(model.instance$`destinationFolderName`, "EXPECTED_RESULT")
})

test_that("metadataToCopy", {
  # tests for the property `metadataToCopy` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`metadataToCopy`, "EXPECTED_RESULT")
})

test_that("duplicateFileAction", {
  # tests for the property `duplicateFileAction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`duplicateFileAction`, "EXPECTED_RESULT")
})
