# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VolumeMigrationOperationParameters")

model_instance <- VolumeMigrationOperationParameters$new()

test_that("volumeId", {
  # tests for the property `volumeId` (character)
  # The volume id for the migration operation

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})
