# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskRunSummaryPagedItems")

model_instance <- TaskRunSummaryPagedItems$new()

test_that("items", {
  # tests for the property `items` (array[TaskRunSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("itemCount", {
  # tests for the property `itemCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`itemCount`, "EXPECTED_RESULT")
})

test_that("firstPageToken", {
  # tests for the property `firstPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`firstPageToken`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("prevPageToken", {
  # tests for the property `prevPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`prevPageToken`, "EXPECTED_RESULT")
})

test_that("lastPageToken", {
  # tests for the property `lastPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastPageToken`, "EXPECTED_RESULT")
})

test_that("totalItemCount", {
  # tests for the property `totalItemCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalItemCount`, "EXPECTED_RESULT")
})

test_that("totalPageCount", {
  # tests for the property `totalPageCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalPageCount`, "EXPECTED_RESULT")
})
