# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MountMappingWithCreds")

model_instance <- MountMappingWithCreds$new()

test_that("path", {
  # tests for the property `path` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("storageProvider", {
  # tests for the property `storageProvider` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageProvider`, "EXPECTED_RESULT")
})

test_that("credentials", {
  # tests for the property `credentials` (map(character))

  # uncomment below to test the property
  #expect_equal(model.instance$`credentials`, "EXPECTED_RESULT")
})

test_that("serviceUrl", {
  # tests for the property `serviceUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`serviceUrl`, "EXPECTED_RESULT")
})
