# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaskRunLogs")

model_instance <- TaskRunLogs$new()

test_that("startTime", {
  # tests for the property `startTime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`startTime`, "EXPECTED_RESULT")
})

test_that("endTime", {
  # tests for the property `endTime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`endTime`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("errorDetails", {
  # tests for the property `errorDetails` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`errorDetails`, "EXPECTED_RESULT")
})

test_that("stdout", {
  # tests for the property `stdout` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`stdout`, "EXPECTED_RESULT")
})

test_that("stderr", {
  # tests for the property `stderr` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`stderr`, "EXPECTED_RESULT")
})
