# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ErrorResponse3")

model_instance <- ErrorResponse3$new()

test_that("code", {
  # tests for the property `code` (character)
  # Error code which uniquely identifies the type of error which occurred

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # Description of the error which occurred

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("details", {
  # tests for the property `details` (array[object])
  # Additional details for conditions which caused the error

  # uncomment below to test the property
  #expect_equal(model.instance$`details`, "EXPECTED_RESULT")
})
