# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowRunsApi")

api_instance <- WorkflowRunsApi$new()

test_that("AbortWorkflowRun", {
  # tests for AbortWorkflowRun
  # base path: http://aps2.platform.illumina.com
  # Abort a workflow run
  # Aborts the workflow run with a given ID.
  # @param run_id character ID of the workflow run
  # @param include array[character] Comma-separated list of properties to include in the response (optional)
  # @param body AbortWorkflowRunRequest  (optional)
  # @return [WorkflowRun]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetWorkflowRun", {
  # tests for GetWorkflowRun
  # base path: http://aps2.platform.illumina.com
  # Get the details of a workflow run
  # Gets the details of a workflow run with a given ID.
  # @param run_id character ID of the workflow run
  # @param include array[character] Comma-separated list of properties to include in the response (optional)
  # @return [WorkflowRun]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListWorkflowRunHistory", {
  # tests for ListWorkflowRunHistory
  # base path: http://aps2.platform.illumina.com
  # Get a list of workflow run history events
  # Gets a list of history events for a workflow run with a given ID.
  # @param run_id character ID of the workflow run
  # @param sort character  (optional)
  # @param include array[character] Comma-separated list of properties to include in the response (optional)
  # @param page_size integer Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (optional)
  # @param page_token character Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (optional)
  # @return [WorkflowRunHistoryEventList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListWorkflowRuns", {
  # tests for ListWorkflowRuns
  # base path: http://aps2.platform.illumina.com
  # Get a list of workflow runs
  # Gets a list of workflow runs.
  # @param status array[character]  (optional)
  # @param tenant_id character ID of the tenant (optional)
  # @param name character  (optional)
  # @param include array[character] Comma-separated list of properties to include in the response (optional)
  # @param page_size integer Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (optional)
  # @param page_token character Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (optional)
  # @param sort character Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (optional)
  # @return [WorkflowRunList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
