# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FolderUpdateRequest")

model_instance <- FolderUpdateRequest$new()

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this folder and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Optional array to replace the acl on the resource.

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})
