# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileCopyOperationParameters")

model_instance <- FileCopyOperationParameters$new()

test_that("sourceVolumeId", {
  # tests for the property `sourceVolumeId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceVolumeId`, "EXPECTED_RESULT")
})

test_that("sourceFileIds", {
  # tests for the property `sourceFileIds` (array[character])
  # The file Ids for the copy operation

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceFileIds`, "EXPECTED_RESULT")
})

test_that("targetFolderId", {
  # tests for the property `targetFolderId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`targetFolderId`, "EXPECTED_RESULT")
})

test_that("metadataToCopy", {
  # tests for the property `metadataToCopy` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`metadataToCopy`, "EXPECTED_RESULT")
})

test_that("duplicateFileAction", {
  # tests for the property `duplicateFileAction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`duplicateFileAction`, "EXPECTED_RESULT")
})
