# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobResponse")

model_instance <- JobResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # A unique identifier for this Job

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("parentFolderUrn", {
  # tests for the property `parentFolderUrn` (character)
  # The Universal Resource Name of the parent folder associated with the Job

  # uncomment below to test the property
  #expect_equal(model.instance$`parentFolderUrn`, "EXPECTED_RESULT")
})

test_that("operationType", {
  # tests for the property `operationType` (JobOperationType)

  # uncomment below to test the property
  #expect_equal(model.instance$`operationType`, "EXPECTED_RESULT")
})

test_that("jobType", {
  # tests for the property `jobType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jobType`, "EXPECTED_RESULT")
})

test_that("operationParameters", {
  # tests for the property `operationParameters` (JobOperationParameters)

  # uncomment below to test the property
  #expect_equal(model.instance$`operationParameters`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (JobOutput)

  # uncomment below to test the property
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

test_that("progressStatus", {
  # tests for the property `progressStatus` (JobProgressStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`progressStatus`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # The date &amp; time this Folder was created, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The creator of this Job

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("timeModified", {
  # tests for the property `timeModified` (character)
  # The date &amp; time this Job was updated, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeModified`, "EXPECTED_RESULT")
})

test_that("timeCompleted", {
  # tests for the property `timeCompleted` (character)
  # The date &amp; time this Job was completed, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCompleted`, "EXPECTED_RESULT")
})
