# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TasksApi")

api_instance <- TasksApi$new()

test_that("CreateTask", {
  # tests for CreateTask
  # base path: http://aps2.platform.illumina.com
  # Create a Task
  # Creates a task. Returns the ID associated with the new task. Also returns the task version ID associated with the new task, if provided. Substitutions can be defined in the following format: \&quot;{{string}}\&quot;, and specified at launch time.
  # @param body CreateTaskRequest  (optional)
  # @return [Task]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTask", {
  # tests for GetTask
  # base path: http://aps2.platform.illumina.com
  # Get the details of a Task
  # Gets the details of a Task for a given task ID.
  # @param task_id character 
  # @return [TaskSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTasks", {
  # tests for ListTasks
  # base path: http://aps2.platform.illumina.com
  # Get a list of tasks
  # Gets a list of tasks accessible by the current tenant ID.
  # @param names character Name: Optional parameter to filter the returned list. Case-Sensitive (optional)
  # @param acls character Name: Optional parameter to filter the returned list. Case-Sensitive (optional)
  # @param page_size integer Optional parameter to define the page size returned. Valid inputs range from 1-1000. (optional)
  # @param sort character Sort: Optional parameter to set the sort of the returned list. Valid fields include: name, timeCreated, timeModified.  The sort can be specified as asc or desc. (Default: asc.) (optional)
  # @param page_token character pageToken: Optional parameter for navigation after initial listing. Valid values include firstPageToken,  nextPageToken, and previousPageToken (provided in the list response) (optional)
  # @return [TaskSummaryPagedItems]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateTask", {
  # tests for UpdateTask
  # base path: http://aps2.platform.illumina.com
  # Update an existing task.
  # Updates the task with a given ID. The task&#39;s name, description can be updated. The task&#39;s name must remain unique.
  # @param task_id character 
  # @param body UpdateTaskRequest Details of the task to be updated. (optional)
  # @return [Task]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
