# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateWorkflowVersionRequest")

model_instance <- CreateWorkflowVersionRequest$new()

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (WorkflowLanguage)

  # uncomment below to test the property
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("definition", {
  # tests for the property `definition` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`definition`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Published Status of the workflow version

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})
