# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartEtag")

model_instance <- PartEtag$new()

test_that("part", {
  # tests for the property `part` (integer)
  # Part number

  # uncomment below to test the property
  #expect_equal(model.instance$`part`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)
  # Etag response for the part upload

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})
