# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FoldersApi")

api_instance <- FoldersApi$new()

test_that("ArchiveFolder", {
  # tests for ArchiveFolder
  # base path: http://aps2.platform.illumina.com
  # Archive a folder
  # Archives a folder to a lower storage cost tier.
  # @param folder_id character Unique identifier for the folder to be archived.
  # @param body FolderArchiveRequest 
  # @return [FolderResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BulkFolderUpdate", {
  # tests for BulkFolderUpdate
  # base path: http://aps2.platform.illumina.com
  # Updates list of folders with metadata
  # Updates list of folders with metadata
  # @param body BulkFolderUpdateRequest  (optional)
  # @return [BulkFolderUpdateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BulkMetadataFolderUpdate", {
  # tests for BulkMetadataFolderUpdate
  # base path: http://aps2.platform.illumina.com
  # Updates list of folders with metadata
  # Updates list of folders with metadata
  # @param body BulkFolderMetadataUpdateRequest  (optional)
  # @return [JobResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CompleteFolderSession", {
  # tests for CompleteFolderSession
  # base path: http://aps2.platform.illumina.com
  # Complete a folder upload in GDS
  # Complete a folder upload in GDS.
  # @param folder_id character Unique identifier for the folder related to the upload session.
  # @param session_id character The id of the upload session
  # @param body CompleteSessionRequest The request body
  # @return [SessionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CopyFolder", {
  # tests for CopyFolder
  # base path: http://aps2.platform.illumina.com
  # Copy a folder
  # Copy a folder into a target parent folder
  # @param folder_id character Unique identifier for the folder to be copied.
  # @param body FolderCopyRequest 
  # @param tenant_id character Optional parameter to copy from a shared folder in another tenant (optional)
  # @return [JobResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateFolder", {
  # tests for CreateFolder
  # base path: http://aps2.platform.illumina.com
  # Create a folder in GDS and receive credentials for upload
  # Create a folder entry in GDS. Returns temporary credentials for folder upload directly to S3 when the include&#x3D;objectStoreAccess parameter is used. Volume ID or volume name is required for folder creation. If a folder path is provided and does not exist, GDS automatically creates the folder path in the appropriate account.
  # @param body CreateFolderRequest 
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @return [FolderWriteableResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateFolderSession", {
  # tests for CreateFolderSession
  # base path: http://aps2.platform.illumina.com
  # Create a session
  # Create a session and credentials used for accessing the object store directly
  # @param folder_id character 
  # @param body CreateSessionRequest 
  # @return [CreateSessionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteFolder", {
  # tests for DeleteFolder
  # base path: http://aps2.platform.illumina.com
  # Deletes a folder by id
  # @param folder_id character Unique identifier for the folder to be deleted.
  # @return [FolderResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFolder", {
  # tests for GetFolder
  # base path: http://aps2.platform.illumina.com
  # Get information about a folder in GDS.
  # Get information for the specified folder ID.
  # @param folder_id character Unique identifier for the folder to retrieve.
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param include_volume_metadata character Optional parameter to return volume's metadata (optional)
  # @param include_active_jobs character Optional parameter to return active jobs associated to folder (optional)
  # @param metadata_include character Optional parameter to specify comma separated patterns to include metadata by their field names. (optional)
  # @param metadata_exclude character Optional parameter to specify comma separated patterns to exclude metadata by their field names. (optional)
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @return [FolderResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFolderJob", {
  # tests for GetFolderJob
  # base path: http://aps2.platform.illumina.com
  # Get status of a folder job in GDS
  # Get status of a folder job in GDS.
  # @param folder_id character Unique identifier for the folder related to the job.
  # @param job_id character The id of the job
  # @return [JobResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetFolderSession", {
  # tests for GetFolderSession
  # base path: http://aps2.platform.illumina.com
  # Get status of a folder upload in GDS
  # Get status of a folder upload in GDS.
  # @param folder_id character Unique identifier for the folder related to the upload session.
  # @param session_id character The id of the upload session
  # @return [SessionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListFolders", {
  # tests for ListFolders
  # base path: http://aps2.platform.illumina.com
  # Get a list of folders
  # Given a volumeId or volume name, get a list of folders accessible by the JWT. The default sort returned is alphabetical, ascending. The default page size is 10 items
  # @param volume_id array[character] Optional field that specifies comma-separated volume IDs to include in the list (optional)
  # @param volume_name array[character] Optional field that specifies comma-separated volume names to include in the list (optional)
  # @param path array[character] Optional field that specifies comma-separated paths to include in the list. Value can use wildcards (e.g. /a/b/c/*) or exact matches (e.g. /a/b/c/d/). (optional)
  # @param job_statuses character Optional field that specifies comma-separated JobStatuses to include in the list (optional)
  # @param acls array[character] Optional field that specifies comma-separated acls to include in the list (optional)
  # @param recursive character Optional field to specify if folders should be returned recursively in and under the specified paths, or only directly in the specified paths (optional)
  # @param page_size integer START_DESC END_DESC (optional)
  # @param page_token character START_DESC END_DESC (optional)
  # @param include character Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl (optional)
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param metadata_include character Optional parameter to specify comma separated patterns to include metadata by their field names. (optional)
  # @param metadata_exclude character Optional parameter to specify comma separated patterns to exclude metadata by their field names. (optional)
  # @return [FolderListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UnarchiveFolder", {
  # tests for UnarchiveFolder
  # base path: http://aps2.platform.illumina.com
  # Unarchive a folder
  # Unarchive a folder from a lower storage cost tier.
  # @param folder_id character Unique identifier for the folder to be unarchived.
  # @param body FolderUnarchiveRequest 
  # @return [FolderResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateFolder", {
  # tests for UpdateFolder
  # base path: http://aps2.platform.illumina.com
  # Update a folder content or acl
  # Update an existing folder in GDS and return upload credentials for that folder. Changes to the folder name and other metadata are not supported at this time.  Optionally overwrite the acl for this folder if acl is provided in the request.
  # @param folder_id character Unique identifier for the folder to be updated.
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @param body FolderUpdateRequest  (optional)
  # @return [FolderWriteableResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
