# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowRunHistoryEvent")

model_instance <- WorkflowRunHistoryEvent$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name of the event, such as the name of the step/task for state-level events and run name for run-level events

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("eventId", {
  # tests for the property `eventId` (integer)
  # Identifier for the history event, if any

  # uncomment below to test the property
  #expect_equal(model.instance$`eventId`, "EXPECTED_RESULT")
})

test_that("previousEventId", {
  # tests for the property `previousEventId` (integer)
  # Identifier for any previous history event (if available)

  # uncomment below to test the property
  #expect_equal(model.instance$`previousEventId`, "EXPECTED_RESULT")
})

test_that("eventType", {
  # tests for the property `eventType` (character)
  # Type of history event. The associated details entry will be populated based on the type of event.

  # uncomment below to test the property
  #expect_equal(model.instance$`eventType`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # Timestamp for the history event

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("eventDetails", {
  # tests for the property `eventDetails` (object)
  # Details for history event

  # uncomment below to test the property
  #expect_equal(model.instance$`eventDetails`, "EXPECTED_RESULT")
})
