# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileUploadCompleteRequest")

model_instance <- FileUploadCompleteRequest$new()

test_that("multipartUploadId", {
  # tests for the property `multipartUploadId` (character)
  # The multipart upload id used by the object store

  # uncomment below to test the property
  #expect_equal(model.instance$`multipartUploadId`, "EXPECTED_RESULT")
})

test_that("partEtags", {
  # tests for the property `partEtags` (array[PartEtag])
  # etags for each uploaded part (optional for files that uses multipart upload)

  # uncomment below to test the property
  #expect_equal(model.instance$`partEtags`, "EXPECTED_RESULT")
})
