# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FolderWriteableResponse")

model_instance <- FolderWriteableResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # A unique identifier for this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("volumeId", {
  # tests for the property `volumeId` (character)
  # The unique identifier for this Folder&#39;s Volume

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})

test_that("parentFolderId", {
  # tests for the property `parentFolderId` (character)
  # The unique identifier for this folder&#39;s parent folder

  # uncomment below to test the property
  #expect_equal(model.instance$`parentFolderId`, "EXPECTED_RESULT")
})

test_that("volumeName", {
  # tests for the property `volumeName` (character)
  # The name of this Folder&#39;s Volume

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeName`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)
  # The unique identifier for this Folders&#39;s Tenant

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("subTenantId", {
  # tests for the property `subTenantId` (character)
  # The unique identifier for this Folder&#39;s Sub Tenant

  # uncomment below to test the property
  #expect_equal(model.instance$`subTenantId`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)
  # The Universal Resource Name, unique to this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (character)
  # The (GDS) folder path to this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # The list of directly specified Id(s) that have access to this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("inheritedAcl", {
  # tests for the property `inheritedAcl` (array[character])
  # The inherited list of Id(s) that have access to this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`inheritedAcl`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # The date &amp; time this Folder was created, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The creator of this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("timeModified", {
  # tests for the property `timeModified` (character)
  # The date &amp; time this Folder was updated, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeModified`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # The updator of this Folder

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this folder

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("volumeMetadata", {
  # tests for the property `volumeMetadata` (object)
  # Metadata about this folder&#39;s volume

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeMetadata`, "EXPECTED_RESULT")
})

test_that("jobStatus", {
  # tests for the property `jobStatus` (JobStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`jobStatus`, "EXPECTED_RESULT")
})

test_that("jobId", {
  # tests for the property `jobId` (character)
  # The job identifier for the current folder operation. Currently only being used for the delete folder operation.

  # uncomment below to test the property
  #expect_equal(model.instance$`jobId`, "EXPECTED_RESULT")
})

test_that("archiveJobStorageTier", {
  # tests for the property `archiveJobStorageTier` (StorageTier)

  # uncomment below to test the property
  #expect_equal(model.instance$`archiveJobStorageTier`, "EXPECTED_RESULT")
})

test_that("migrationStatus", {
  # tests for the property `migrationStatus` (character)
  # Status of the root folder migration status from v1 to v2

  # uncomment below to test the property
  #expect_equal(model.instance$`migrationStatus`, "EXPECTED_RESULT")
})

test_that("activeJobIds", {
  # tests for the property `activeJobIds` (array[character])
  # List of Jobs in Pending and In Progress status

  # uncomment below to test the property
  #expect_equal(model.instance$`activeJobIds`, "EXPECTED_RESULT")
})

test_that("objectStoreAccess", {
  # tests for the property `objectStoreAccess` (ObjectStoreAccess)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectStoreAccess`, "EXPECTED_RESULT")
})
