# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkFileUpdateItem")

model_instance <- BulkFileUpdateItem$new()

test_that("id", {
  # tests for the property `id` (character)
  # Id of this file

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this file and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)
  # The File&#39;s Format

  # uncomment below to test the property
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

test_that("formatEdam", {
  # tests for the property `formatEdam` (character)
  # The File&#39;s Edam Format

  # uncomment below to test the property
  #expect_equal(model.instance$`formatEdam`, "EXPECTED_RESULT")
})

test_that("lifeCycle", {
  # tests for the property `lifeCycle` (FileLifeCycleSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`lifeCycle`, "EXPECTED_RESULT")
})
