# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileWriteableResponse")

model_instance <- FileWriteableResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # A unique identifier for this File

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of this File

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("volumeId", {
  # tests for the property `volumeId` (character)
  # The unique identifier of the volume where the file resides

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})

test_that("parentFolderId", {
  # tests for the property `parentFolderId` (character)
  # The unique identifier of the folder where the file resides

  # uncomment below to test the property
  #expect_equal(model.instance$`parentFolderId`, "EXPECTED_RESULT")
})

test_that("volumeName", {
  # tests for the property `volumeName` (character)
  # The name of the volume where the file resides

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeName`, "EXPECTED_RESULT")
})

test_that("volumeConfigurationName", {
  # tests for the property `volumeConfigurationName` (character)
  # The name of the volume configuration (BYOB only)

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeConfigurationName`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # The type of the File

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)
  # The unique identifier for this File&#39;s Tenant

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("subTenantId", {
  # tests for the property `subTenantId` (character)
  # The unique identifier for this File&#39;s Sub Tenant

  # uncomment below to test the property
  #expect_equal(model.instance$`subTenantId`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (character)
  # The (GDS) path to this File

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # The date &amp; time this File was created, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The creator of this File

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("timeModified", {
  # tests for the property `timeModified` (character)
  # The date &amp; time this File was updated, in GDS

  # uncomment below to test the property
  #expect_equal(model.instance$`timeModified`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # The updator of this File

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("inheritedAcl", {
  # tests for the property `inheritedAcl` (array[character])
  # The inherited list of Id(s) that have access to this File

  # uncomment below to test the property
  #expect_equal(model.instance$`inheritedAcl`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)
  # The Universal Resource Name, unique to this File

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("sizeInBytes", {
  # tests for the property `sizeInBytes` (integer)
  # The File&#39;s Size in bytes

  # uncomment below to test the property
  #expect_equal(model.instance$`sizeInBytes`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this File

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("isUploaded", {
  # tests for the property `isUploaded` (character)
  # The current upload state of the File

  # uncomment below to test the property
  #expect_equal(model.instance$`isUploaded`, "EXPECTED_RESULT")
})

test_that("archiveStatus", {
  # tests for the property `archiveStatus` (ArchiveStatuses)

  # uncomment below to test the property
  #expect_equal(model.instance$`archiveStatus`, "EXPECTED_RESULT")
})

test_that("timeArchived", {
  # tests for the property `timeArchived` (character)
  # The date &amp; time this File was archived

  # uncomment below to test the property
  #expect_equal(model.instance$`timeArchived`, "EXPECTED_RESULT")
})

test_that("storageTier", {
  # tests for the property `storageTier` (StorageTier)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageTier`, "EXPECTED_RESULT")
})

test_that("eTag", {
  # tests for the property `eTag` (character)
  # The File&#39;s ETag

  # uncomment below to test the property
  #expect_equal(model.instance$`eTag`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)
  # The File&#39;s Format

  # uncomment below to test the property
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

test_that("formatEdam", {
  # tests for the property `formatEdam` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`formatEdam`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (FileStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("lifeCycle", {
  # tests for the property `lifeCycle` (FileLifeCycleSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`lifeCycle`, "EXPECTED_RESULT")
})

test_that("versionId", {
  # tests for the property `versionId` (character)
  # Id of the latest version of the object in the object container

  # uncomment below to test the property
  #expect_equal(model.instance$`versionId`, "EXPECTED_RESULT")
})

test_that("objectStoreAccess", {
  # tests for the property `objectStoreAccess` (ObjectStoreAccess)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectStoreAccess`, "EXPECTED_RESULT")
})
