# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VolumeFileListRequest")

model_instance <- VolumeFileListRequest$new()

test_that("volumeId", {
  # tests for the property `volumeId` (character)
  # Volume identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeId`, "EXPECTED_RESULT")
})

test_that("fileIds", {
  # tests for the property `fileIds` (array[character])
  # File identifiers to list

  # uncomment below to test the property
  #expect_equal(model.instance$`fileIds`, "EXPECTED_RESULT")
})

test_that("includePresignedUrl", {
  # tests for the property `includePresignedUrl` (character)
  # Optional parameter that returns presigned URL for each file when set to true

  # uncomment below to test the property
  #expect_equal(model.instance$`includePresignedUrl`, "EXPECTED_RESULT")
})

test_that("presignedUrlMode", {
  # tests for the property `presignedUrlMode` (character)
  # Optional parameter to specify presigned url&#39;s content-disposition. If not specified, the browser will determine the default behavior.  Possible values: Attachment, Inline, Browser

  # uncomment below to test the property
  #expect_equal(model.instance$`presignedUrlMode`, "EXPECTED_RESULT")
})
