# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Workflow")

model_instance <- Workflow$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique resource ID

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)
  # URN of the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (character)
  # HREF to the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the workflow

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("organization", {
  # tests for the property `organization` (character)
  # Organization associated with the workflow

  # uncomment below to test the property
  #expect_equal(model.instance$`organization`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of the workflow

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("toolClass", {
  # tests for the property `toolClass` (character)
  # Workflow type

  # uncomment below to test the property
  #expect_equal(model.instance$`toolClass`, "EXPECTED_RESULT")
})

test_that("categories", {
  # tests for the property `categories` (array[character])
  # Categories of the workflow (Limit Max Size : 10)

  # uncomment below to test the property
  #expect_equal(model.instance$`categories`, "EXPECTED_RESULT")
})

test_that("createdByClientId", {
  # tests for the property `createdByClientId` (character)
  # Client ID of the Origin Request

  # uncomment below to test the property
  #expect_equal(model.instance$`createdByClientId`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # Time (in UTC) the resource was created

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("timeModified", {
  # tests for the property `timeModified` (character)
  # Time (in UTC) the resource was modified

  # uncomment below to test the property
  #expect_equal(model.instance$`timeModified`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # User that created the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # User that modified the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)
  # Tenant ID the resource belongs to

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Access control list of the resource

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})
