# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VolumesApi")

api_instance <- VolumesApi$new()

test_that("CreateVolume", {
  # tests for CreateVolume
  # base path: http://aps2.platform.illumina.com
  # Create a volume in GDS and receive temporary credentials for upload
  # Create a volume in GDS to hold folders and files. Returns upload credentials to the root folder of the volume when the include&#x3D;objectStoreAccess parameter is used. You must create a volume prior to uploading files or folders.
  # @param body CreateVolumeRequest 
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @return [CreateVolumeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteVolume", {
  # tests for DeleteVolume
  # base path: http://aps2.platform.illumina.com
  # Deletes a volume by Id
  # @param volume_id character Unique identifier for the Volume to be deleted.
  # @param purge_object_store_data character Optional and for BYOB only. If true, the volume's data in object storage will be erased.              This field is ignored for non-BYOB volumes where the object store data is always removed upon deleting the volume. (optional)
  # @return [VolumeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetVolume", {
  # tests for GetVolume
  # base path: http://aps2.platform.illumina.com
  # Get information for the specified volume ID or volume name
  # @param volume_id character Unique identifier for the volume to retrieve information for.
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param metadata_include character Optional parameter to specify comma separated patterns to include metadata by their field names. (optional)
  # @param metadata_exclude character Optional parameter to specify comma separated patterns to exclude metadata by their field names. (optional)
  # @return [VolumeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListVolumes", {
  # tests for ListVolumes
  # base path: http://aps2.platform.illumina.com
  # Get a list of volumes
  # Get a list of volumes accessible by the current JWT token’s tenant ID in GDS. The default sort returned is alphabetical, ascending. The default page size is 10 items.
  # @param page_size integer START_DESC END_DESC (optional)
  # @param page_token character START_DESC END_DESC (optional)
  # @param include character Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl (optional)
  # @param tenant_id character Optional parameter to see shared data in another tenant (optional)
  # @param volume_configuration_name character Unique name of the volume configuration (optional)
  # @return [VolumeListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateVolume", {
  # tests for UpdateVolume
  # base path: http://aps2.platform.illumina.com
  # Update a volume content
  # Update an existing volume in GDS and return upload credentials for that volume. 
  # @param volume_id character Unique identifier for the volume to be updated.
  # @param include character Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (optional)
  # @param body UpdateVolumeRequest  (optional)
  # @return [VolumeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
