# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Subscription")

model_instance <- Subscription$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique id of the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("urn", {
  # tests for the property `urn` (character)
  # URN of the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`urn`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Type of event the subscription matches

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("actions", {
  # tests for the property `actions` (array[character])
  # Types of actions the subscription matches for the event type

  # uncomment below to test the property
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("filterExpression", {
  # tests for the property `filterExpression` (character)
  # JSON-structured filter expression for events matching the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`filterExpression`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Optional description for the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("deliveryTarget", {
  # tests for the property `deliveryTarget` (DeliveryTarget)

  # uncomment below to test the property
  #expect_equal(model.instance$`deliveryTarget`, "EXPECTED_RESULT")
})

test_that("matchIdentities", {
  # tests for the property `matchIdentities` (array[character])
  # ACL Identities for events the subscription matches

  # uncomment below to test the property
  #expect_equal(model.instance$`matchIdentities`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # The list of identities that have access to this subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)
  # Tenant id of the subscription owner

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("createdByUserId", {
  # tests for the property `createdByUserId` (character)
  # User id for the creator of the subscription

  # uncomment below to test the property
  #expect_equal(model.instance$`createdByUserId`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)
  # Timestamp when the subscription was created

  # uncomment below to test the property
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("deletedByUserId", {
  # tests for the property `deletedByUserId` (character)
  # Id of the user who deleted the subscription, if applicable

  # uncomment below to test the property
  #expect_equal(model.instance$`deletedByUserId`, "EXPECTED_RESULT")
})

test_that("timeDeleted", {
  # tests for the property `timeDeleted` (character)
  # Timestamp when the subscription was deleted, if applicable

  # uncomment below to test the property
  #expect_equal(model.instance$`timeDeleted`, "EXPECTED_RESULT")
})

test_that("isDeleted", {
  # tests for the property `isDeleted` (character)
  # Whether or not the subscription has been deleted

  # uncomment below to test the property
  #expect_equal(model.instance$`isDeleted`, "EXPECTED_RESULT")
})
