# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeliveryTargetAwsSnsTopic")

model_instance <- DeliveryTargetAwsSnsTopic$new()

test_that("topicArn", {
  # tests for the property `topicArn` (character)
  # ARN for the AWS SNS topic

  # uncomment below to test the property
  #expect_equal(model.instance$`topicArn`, "EXPECTED_RESULT")
})
