# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowArgument")

model_instance <- WorkflowArgument$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name of the argument key

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)
  # A simple string value for the argument. Cannot provide both Value and Json at the same time.

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("json", {
  # tests for the property `json` (object)
  # A JSON value for the argument. Cannot provide both Value and Json at the same time.

  # uncomment below to test the property
  #expect_equal(model.instance$`json`, "EXPECTED_RESULT")
})

test_that("options", {
  # tests for the property `options` (character)
  # Comma separated list of options for the argument: Required, Overridable, Writable, Json, Optional, ReadOnly, Final  Some combinations of options are considered errors, like Required/Optional, Overridable/Final, Writable/ReadOnly, etc.

  # uncomment below to test the property
  #expect_equal(model.instance$`options`, "EXPECTED_RESULT")
})
