# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateTaskRequest")

model_instance <- CreateTaskRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # User-defined name of the task

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # User-defined description of the task

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("acl", {
  # tests for the property `acl` (array[character])
  # Access Control List

  # uncomment below to test the property
  #expect_equal(model.instance$`acl`, "EXPECTED_RESULT")
})

test_that("taskVersions", {
  # tests for the property `taskVersions` (array[CreateTaskVersionRequest])
  # List of task versions

  # uncomment below to test the property
  #expect_equal(model.instance$`taskVersions`, "EXPECTED_RESULT")
})
