# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ObjectStoreAccess")

model_instance <- ObjectStoreAccess$new()

test_that("sessionId", {
  # tests for the property `sessionId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sessionId`, "EXPECTED_RESULT")
})

test_that("awsS3TemporaryUploadCredentials", {
  # tests for the property `awsS3TemporaryUploadCredentials` (AwsS3TemporaryUploadCredentials)

  # uncomment below to test the property
  #expect_equal(model.instance$`awsS3TemporaryUploadCredentials`, "EXPECTED_RESULT")
})

test_that("awsS3PresignedUrlForUpload", {
  # tests for the property `awsS3PresignedUrlForUpload` (AwsS3PresignedUrlForUpload)

  # uncomment below to test the property
  #expect_equal(model.instance$`awsS3PresignedUrlForUpload`, "EXPECTED_RESULT")
})

test_that("awsS3TemporaryReadOnlyCredentials", {
  # tests for the property `awsS3TemporaryReadOnlyCredentials` (AwsS3TemporaryReadOnlyCredentials)

  # uncomment below to test the property
  #expect_equal(model.instance$`awsS3TemporaryReadOnlyCredentials`, "EXPECTED_RESULT")
})
