# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetadataUpdateRequest")

model_instance <- MetadataUpdateRequest$new()

test_that("updateMetadata", {
  # tests for the property `updateMetadata` (object)
  # Metadata to update.

  # uncomment below to test the property
  #expect_equal(model.instance$`updateMetadata`, "EXPECTED_RESULT")
})

test_that("deleteMetadata", {
  # tests for the property `deleteMetadata` (object)
  # Metadata to delete.

  # uncomment below to test the property
  #expect_equal(model.instance$`deleteMetadata`, "EXPECTED_RESULT")
})
