# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContainerStateRunning")

model_instance <- ContainerStateRunning$new()

test_that("startedAt", {
  # tests for the property `startedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`startedAt`, "EXPECTED_RESULT")
})
