# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateVolumeRequest")

model_instance <- CreateVolumeRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name for the volume

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("volumeConfigurationName", {
  # tests for the property `volumeConfigurationName` (character)
  # Unique name of the volume configuration to use

  # uncomment below to test the property
  #expect_equal(model.instance$`volumeConfigurationName`, "EXPECTED_RESULT")
})

test_that("rootKeyPrefix", {
  # tests for the property `rootKeyPrefix` (character)
  # The base bucket location for volumes associated with custom VolumeConfigurations. If not provided, the given volume Name is used.  If provided, it must start with the VolumeConfiguration&#39;s keyprefix and end with a /.  To create a volume representing the root of a bucket, use the value &#39;/&#39;.

  # uncomment below to test the property
  #expect_equal(model.instance$`rootKeyPrefix`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Metadata about this volume and its contents

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

test_that("lifeCycle", {
  # tests for the property `lifeCycle` (VolumeLifeCycleSettings)

  # uncomment below to test the property
  #expect_equal(model.instance$`lifeCycle`, "EXPECTED_RESULT")
})
