#' Workflow Execution Service
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Subscriptions operations
#' @description SubscriptionsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateSubscription } \emph{ Creates a subscription to an event type and defines how those events get delivered. }
#' Events can be delivered to AWS SQS, AWS SNS, or can be used to launch a WES workflow.
#'
#' \itemize{
#' \item \emph{ @param } body \link{CreateSubscriptionRequest}
#' \item \emph{ @returnType } \link{Subscription} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 201 | The subscription is created successfully.
#'
#' \item return type : Subscription
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | An invalid or missing input parameter will result in a bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | The acting identity cannot be authenticated and authorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | The acting identity is not authorized to subscribe to the given event type or deliver to the given delivery target.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | The given delivery target is not valid or cannot be delivered to.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DisableSubscription } \emph{ Given a subscription id, disables the specified subscription. }
#' Given a subscription id, disables that subscription with the current JWT token’s tenant Id.
#'
#' \itemize{
#' \item \emph{ @param } subscription_id character
#' \item \emph{ @returnType } \link{Subscription} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Subscription for the given ID is disabled successfully.
#'
#' \item return type : Subscription
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | An invalid or missing input parameter will result in a bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | The acting identity cannot be authenticated and authorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | The acting identity is not authorized to disable the subscription for the given ID.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Could not find a subscription for the given ID.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 410 | The subscription for the given ID has been disabled.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetSubscription } \emph{ Given a subscription id, returns information about that subscription. }
#' Given a subscription id, returns information about that subscription accessible by the current JWT token’s tenant Id.
#'
#' \itemize{
#' \item \emph{ @param } subscription_id character
#' \item \emph{ @returnType } \link{Subscription} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Subscription for the given ID is found and returned successfully.
#'
#' \item return type : Subscription
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | An invalid or missing input parameter will result in a bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | The acting identity cannot be authenticated and authorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | The acting identity is not authorized to access the subscription for the given ID.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Could not find a subscription for the given ID.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 410 | The subscription for the given ID has been disabled.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListSubscriptions } \emph{ Get a list of subscriptions. }
#' Get a list of subscriptions accessible by the current JWT token’s tenant Id.
#'
#' \itemize{
#' \item \emph{ @param } event_type character
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @returnType } \link{SubscriptionList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Subscriptions found and returned successfully.
#'
#' \item return type : SubscriptionList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | An invalid or missing input parameter will result in a bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | The acting identity cannot be authenticated and authorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | The acting identity is not authorized to access subscriptions.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateSubscription  ####################
#'
#' library(icar1)
#' var_body <- CreateSubscriptionRequest$new("type_example", "name_example", DeliveryTarget$new(DeliveryTargetAwsSnsTopic$new("topicArn_example"), DeliveryTargetAwsSqsQueue$new("queueUrl_example"), DeliveryTargetWorkflowRunLaunch$new("id_example", "version_example", "name_example", 123)), c("actions_example"), "description_example", "filterExpression_example") # CreateSubscriptionRequest |  (Optional)
#'
#' #Creates a subscription to an event type and defines how those events get delivered.
#' api_instance <- SubscriptionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  DisableSubscription  ####################
#'
#' library(icar1)
#' var_subscription_id <- "subscription_id_example" # character | Id of the subscription to be disabled
#'
#' #Given a subscription id, disables the specified subscription.
#' api_instance <- SubscriptionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  GetSubscription  ####################
#'
#' library(icar1)
#' var_subscription_id <- "subscription_id_example" # character | Id of the subscription to return
#'
#' #Given a subscription id, returns information about that subscription.
#' api_instance <- SubscriptionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListSubscriptions  ####################
#'
#' library(icar1)
#' var_event_type <- "event_type_example" # character | Optional event type for filtering returned subscriptions (Optional)
#' var_page_size <- 56 # integer | Optional parameter to define the page size returned. Valid inputs range from 1-1000. (Optional)
#' var_page_token <- "page_token_example" # character | Utilized for navigation after initial listing. Valid values include those of  firstPageToken, nextPageToken, and previousPageToken in the list response.  When there are no more pages, the nextPageToken will be null. (Optional)
#'
#' #Get a list of subscriptions.
#' api_instance <- SubscriptionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
SubscriptionsApi <- R6::R6Class(
  "SubscriptionsApi",
  public = list(
    api_client = NULL,
    #' Initialize a new SubscriptionsApi.
    #'
    #' @description
    #' Initialize a new SubscriptionsApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Creates a subscription to an event type and defines how those events get delivered.
    #'
    #' @description
    #' Creates a subscription to an event type and defines how those events get delivered.
    #'
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Subscription
    #' @export
    CreateSubscription = function(body = NULL, data_file = NULL, ...) {
      local_var_response <- self$CreateSubscriptionWithHttpInfo(body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Creates a subscription to an event type and defines how those events get delivered.
    #'
    #' @description
    #' Creates a subscription to an event type and defines how those events get delivered.
    #'
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Subscription) with additional information such as HTTP status code, headers
    #' @export
    CreateSubscriptionWithHttpInfo = function(body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE


      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/subscriptions"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json-patch+json", "application/json", "text/json", "application/*+json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Subscription", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Given a subscription id, disables the specified subscription.
    #'
    #' @description
    #' Given a subscription id, disables the specified subscription.
    #'
    #' @param subscription_id Id of the subscription to be disabled
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Subscription
    #' @export
    DisableSubscription = function(subscription_id, data_file = NULL, ...) {
      local_var_response <- self$DisableSubscriptionWithHttpInfo(subscription_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Given a subscription id, disables the specified subscription.
    #'
    #' @description
    #' Given a subscription id, disables the specified subscription.
    #'
    #' @param subscription_id Id of the subscription to be disabled
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Subscription) with additional information such as HTTP status code, headers
    #' @export
    DisableSubscriptionWithHttpInfo = function(subscription_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`subscription_id`)) {
        rlang::abort(message = "Missing required parameter `subscription_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `subscription_id`."))
      }

      if (nchar(`subscription_id`) > 255) {
        rlang::abort(message = "Invalid length for `subscription_id` when calling SubscriptionsApi$DisableSubscription, must be smaller than or equal to 255.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid length for $subscription_id when calling SubscriptionsApi.DisableSubscription, must be smaller than or equal to 255."))
      }

      local_var_url_path <- "/v1/subscriptions/{subscriptionId}"
      if (!missing(`subscription_id`)) {
        local_var_url_path <- gsub("\\{subscriptionId\\}", URLencode(as.character(`subscription_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Subscription", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Given a subscription id, returns information about that subscription.
    #'
    #' @description
    #' Given a subscription id, returns information about that subscription.
    #'
    #' @param subscription_id Id of the subscription to return
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Subscription
    #' @export
    GetSubscription = function(subscription_id, data_file = NULL, ...) {
      local_var_response <- self$GetSubscriptionWithHttpInfo(subscription_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Given a subscription id, returns information about that subscription.
    #'
    #' @description
    #' Given a subscription id, returns information about that subscription.
    #'
    #' @param subscription_id Id of the subscription to return
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Subscription) with additional information such as HTTP status code, headers
    #' @export
    GetSubscriptionWithHttpInfo = function(subscription_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`subscription_id`)) {
        rlang::abort(message = "Missing required parameter `subscription_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `subscription_id`."))
      }

      if (nchar(`subscription_id`) > 255) {
        rlang::abort(message = "Invalid length for `subscription_id` when calling SubscriptionsApi$GetSubscription, must be smaller than or equal to 255.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid length for $subscription_id when calling SubscriptionsApi.GetSubscription, must be smaller than or equal to 255."))
      }

      local_var_url_path <- "/v1/subscriptions/{subscriptionId}"
      if (!missing(`subscription_id`)) {
        local_var_url_path <- gsub("\\{subscriptionId\\}", URLencode(as.character(`subscription_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Subscription", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of subscriptions.
    #'
    #' @description
    #' Get a list of subscriptions.
    #'
    #' @param event_type (optional) Optional event type for filtering returned subscriptions
    #' @param page_size (optional) Optional parameter to define the page size returned. Valid inputs range from 1-1000.
    #' @param page_token (optional) Utilized for navigation after initial listing. Valid values include those of  firstPageToken, nextPageToken, and previousPageToken in the list response.  When there are no more pages, the nextPageToken will be null.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return SubscriptionList
    #' @export
    ListSubscriptions = function(event_type = NULL, page_size = NULL, page_token = NULL, data_file = NULL, ...) {
      local_var_response <- self$ListSubscriptionsWithHttpInfo(event_type, page_size, page_token, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of subscriptions.
    #'
    #' @description
    #' Get a list of subscriptions.
    #'
    #' @param event_type (optional) Optional event type for filtering returned subscriptions
    #' @param page_size (optional) Optional parameter to define the page size returned. Valid inputs range from 1-1000.
    #' @param page_token (optional) Utilized for navigation after initial listing. Valid values include those of  firstPageToken, nextPageToken, and previousPageToken in the list response.  When there are no more pages, the nextPageToken will be null.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (SubscriptionList) with additional information such as HTTP status code, headers
    #' @export
    ListSubscriptionsWithHttpInfo = function(event_type = NULL, page_size = NULL, page_token = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (nchar(`event_type`) > 255) {
        rlang::abort(message = "Invalid length for `event_type` when calling SubscriptionsApi$ListSubscriptions, must be smaller than or equal to 255.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid length for $event_type when calling SubscriptionsApi.ListSubscriptions, must be smaller than or equal to 255."))
      }

      if (`page_size` > 1000) {
        rlang::abort(message = "Invalid value for `page_size` when calling SubscriptionsApi$ListSubscriptions, must be smaller than or equal to 1000.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid value for `page_size` when calling SubscriptionsApi$ListSubscriptions, must be smaller than or equal to 1000."))
      }
      if (`page_size` < 1) {
        rlang::abort(message = "Invalid value for `page_size` when calling SubscriptionsApi$ListSubscriptions, must be bigger than or equal to 1.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid value for `page_size` when calling SubscriptionsApi$ListSubscriptions, must be bigger than or equal to 1."))
      }


      query_params[["eventType"]] <- `event_type`

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      local_var_url_path <- "/v1/subscriptions"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "SubscriptionList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
