#' Workflow Execution Service
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Volumes operations
#' @description VolumesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateVolume } \emph{ Create a volume in GDS and receive temporary credentials for upload }
#' Create a volume in GDS to hold folders and files. Returns upload credentials to the root folder of the volume when the include=objectStoreAccess parameter is used. You must create a volume prior to uploading files or folders.
#'
#' \itemize{
#' \item \emph{ @param } body \link{CreateVolumeRequest}
#' \item \emph{ @param } include character
#' \item \emph{ @returnType } \link{CreateVolumeResponse} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 201 | Created new Volume.
#'
#' \item return type : CreateVolumeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Forbidden.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | A conflict was found. Make sure the new Volume doesn't already exist.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteVolume } \emph{ Deletes a volume by Id }
#'
#' \itemize{
#' \item \emph{ @param } volume_id character
#' \item \emph{ @param } purge_object_store_data character
#' \item \emph{ @returnType } \link{VolumeResponse} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 202 | Accepted.
#'
#' \item return type : VolumeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Forbidden.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Volume not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | Conflict
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetVolume } \emph{ Get information for the specified volume ID or volume name }
#'
#' \itemize{
#' \item \emph{ @param } volume_id character
#' \item \emph{ @param } tenant_id character
#' \item \emph{ @param } metadata_include character
#' \item \emph{ @param } metadata_exclude character
#' \item \emph{ @returnType } \link{VolumeResponse} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Success.
#'
#' \item return type : VolumeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Forbidden.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Volume not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListVolumes } \emph{ Get a list of volumes }
#' Get a list of volumes accessible by the current JWT token’s tenant ID in GDS. The default sort returned is alphabetical, ascending. The default page size is 10 items.
#'
#' \itemize{
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @param } include character
#' \item \emph{ @param } tenant_id character
#' \item \emph{ @param } volume_configuration_name character
#' \item \emph{ @returnType } \link{VolumeListResponse} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Success.
#'
#' \item return type : VolumeListResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Forbidden.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateVolume } \emph{ Update a volume content }
#' Update an existing volume in GDS and return upload credentials for that volume.
#'
#' \itemize{
#' \item \emph{ @param } volume_id character
#' \item \emph{ @param } include character
#' \item \emph{ @param } body \link{UpdateVolumeRequest}
#' \item \emph{ @returnType } \link{VolumeResponse} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Success.
#'
#' \item return type : VolumeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Bad request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Forbidden.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Volume not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateVolume  ####################
#'
#' library(icar1)
#' var_body <- CreateVolumeRequest$new("name_example", "volumeConfigurationName_example", "rootKeyPrefix_example", 123, VolumeLifeCycleSettings$new(123, GracePeriodEndAction$new())) # CreateVolumeRequest | 
#' var_include <- "include_example" # character | Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (Optional)
#'
#' #Create a volume in GDS and receive temporary credentials for upload
#' api_instance <- VolumesApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  DeleteVolume  ####################
#'
#' library(icar1)
#' var_volume_id <- "volume_id_example" # character | Unique identifier for the Volume to be deleted.
#' var_purge_object_store_data <- "purge_object_store_data_example" # character | Optional and for BYOB only. If true, the volume's data in object storage will be erased.              This field is ignored for non-BYOB volumes where the object store data is always removed upon deleting the volume. (Optional)
#'
#' #Deletes a volume by Id
#' api_instance <- VolumesApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  GetVolume  ####################
#'
#' library(icar1)
#' var_volume_id <- "volume_id_example" # character | Unique identifier for the volume to retrieve information for.
#' var_tenant_id <- "tenant_id_example" # character | Optional parameter to see shared data in another tenant (Optional)
#' var_metadata_include <- "metadata_include_example" # character | Optional parameter to specify comma separated patterns to include metadata by their field names. (Optional)
#' var_metadata_exclude <- "metadata_exclude_example" # character | Optional parameter to specify comma separated patterns to exclude metadata by their field names. (Optional)
#'
#' #Get information for the specified volume ID or volume name
#' api_instance <- VolumesApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListVolumes  ####################
#'
#' library(icar1)
#' var_page_size <- 56 # integer | START_DESC END_DESC (Optional)
#' var_page_token <- "page_token_example" # character | START_DESC END_DESC (Optional)
#' var_include <- "include_example" # character | Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl (Optional)
#' var_tenant_id <- "tenant_id_example" # character | Optional parameter to see shared data in another tenant (Optional)
#' var_volume_configuration_name <- "volume_configuration_name_example" # character | Unique name of the volume configuration (Optional)
#'
#' #Get a list of volumes
#' api_instance <- VolumesApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  UpdateVolume  ####################
#'
#' library(icar1)
#' var_volume_id <- "volume_id_example" # character | Unique identifier for the volume to be updated.
#' var_include <- "include_example" # character | Optionally include additional fields in the response.              Possible values: ObjectStoreAccess (Optional)
#' var_body <- UpdateVolumeRequest$new(123, VolumeLifeCycleSettings$new(123, GracePeriodEndAction$new())) # UpdateVolumeRequest |  (Optional)
#'
#' #Update a volume content
#' api_instance <- VolumesApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
VolumesApi <- R6::R6Class(
  "VolumesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new VolumesApi.
    #'
    #' @description
    #' Initialize a new VolumesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Create a volume in GDS and receive temporary credentials for upload
    #'
    #' @description
    #' Create a volume in GDS and receive temporary credentials for upload
    #'
    #' @param body 
    #' @param include (optional) Optionally include additional fields in the response.              Possible values: ObjectStoreAccess
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return CreateVolumeResponse
    #' @export
    CreateVolume = function(body, include = NULL, data_file = NULL, ...) {
      local_var_response <- self$CreateVolumeWithHttpInfo(body, include, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Create a volume in GDS and receive temporary credentials for upload
    #'
    #' @description
    #' Create a volume in GDS and receive temporary credentials for upload
    #'
    #' @param body 
    #' @param include (optional) Optionally include additional fields in the response.              Possible values: ObjectStoreAccess
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (CreateVolumeResponse) with additional information such as HTTP status code, headers
    #' @export
    CreateVolumeWithHttpInfo = function(body, include = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`body`)) {
        rlang::abort(message = "Missing required parameter `body`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `body`."))
      }



      query_params[["include"]] <- `include`

      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/volumes"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "CreateVolumeResponse", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Deletes a volume by Id
    #'
    #' @description
    #' Deletes a volume by Id
    #'
    #' @param volume_id Unique identifier for the Volume to be deleted.
    #' @param purge_object_store_data (optional) Optional and for BYOB only. If true, the volume's data in object storage will be erased.              This field is ignored for non-BYOB volumes where the object store data is always removed upon deleting the volume.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return VolumeResponse
    #' @export
    DeleteVolume = function(volume_id, purge_object_store_data = NULL, data_file = NULL, ...) {
      local_var_response <- self$DeleteVolumeWithHttpInfo(volume_id, purge_object_store_data, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Deletes a volume by Id
    #'
    #' @description
    #' Deletes a volume by Id
    #'
    #' @param volume_id Unique identifier for the Volume to be deleted.
    #' @param purge_object_store_data (optional) Optional and for BYOB only. If true, the volume's data in object storage will be erased.              This field is ignored for non-BYOB volumes where the object store data is always removed upon deleting the volume.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (VolumeResponse) with additional information such as HTTP status code, headers
    #' @export
    DeleteVolumeWithHttpInfo = function(volume_id, purge_object_store_data = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`volume_id`)) {
        rlang::abort(message = "Missing required parameter `volume_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `volume_id`."))
      }



      query_params[["purgeObjectStoreData"]] <- `purge_object_store_data`

      local_var_url_path <- "/v1/volumes/{volumeId}"
      if (!missing(`volume_id`)) {
        local_var_url_path <- gsub("\\{volumeId\\}", URLencode(as.character(`volume_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "VolumeResponse", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get information for the specified volume ID or volume name
    #'
    #' @description
    #' Get information for the specified volume ID or volume name
    #'
    #' @param volume_id Unique identifier for the volume to retrieve information for.
    #' @param tenant_id (optional) Optional parameter to see shared data in another tenant
    #' @param metadata_include (optional) Optional parameter to specify comma separated patterns to include metadata by their field names.
    #' @param metadata_exclude (optional) Optional parameter to specify comma separated patterns to exclude metadata by their field names.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return VolumeResponse
    #' @export
    GetVolume = function(volume_id, tenant_id = NULL, metadata_include = NULL, metadata_exclude = NULL, data_file = NULL, ...) {
      local_var_response <- self$GetVolumeWithHttpInfo(volume_id, tenant_id, metadata_include, metadata_exclude, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get information for the specified volume ID or volume name
    #'
    #' @description
    #' Get information for the specified volume ID or volume name
    #'
    #' @param volume_id Unique identifier for the volume to retrieve information for.
    #' @param tenant_id (optional) Optional parameter to see shared data in another tenant
    #' @param metadata_include (optional) Optional parameter to specify comma separated patterns to include metadata by their field names.
    #' @param metadata_exclude (optional) Optional parameter to specify comma separated patterns to exclude metadata by their field names.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (VolumeResponse) with additional information such as HTTP status code, headers
    #' @export
    GetVolumeWithHttpInfo = function(volume_id, tenant_id = NULL, metadata_include = NULL, metadata_exclude = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`volume_id`)) {
        rlang::abort(message = "Missing required parameter `volume_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `volume_id`."))
      }





      query_params[["tenantId"]] <- `tenant_id`

      query_params[["metadata.include"]] <- `metadata_include`

      query_params[["metadata.exclude"]] <- `metadata_exclude`

      local_var_url_path <- "/v1/volumes/{volumeId}"
      if (!missing(`volume_id`)) {
        local_var_url_path <- gsub("\\{volumeId\\}", URLencode(as.character(`volume_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "VolumeResponse", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of volumes
    #'
    #' @description
    #' Get a list of volumes
    #'
    #' @param page_size (optional) START_DESC END_DESC
    #' @param page_token (optional) START_DESC END_DESC
    #' @param include (optional) Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl
    #' @param tenant_id (optional) Optional parameter to see shared data in another tenant
    #' @param volume_configuration_name (optional) Unique name of the volume configuration
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return VolumeListResponse
    #' @export
    ListVolumes = function(page_size = NULL, page_token = NULL, include = NULL, tenant_id = NULL, volume_configuration_name = NULL, data_file = NULL, ...) {
      local_var_response <- self$ListVolumesWithHttpInfo(page_size, page_token, include, tenant_id, volume_configuration_name, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of volumes
    #'
    #' @description
    #' Get a list of volumes
    #'
    #' @param page_size (optional) START_DESC END_DESC
    #' @param page_token (optional) START_DESC END_DESC
    #' @param include (optional) Optionally include additional fields in the response. Multiple fields can be included by comma-separation.  Possible values: TotalItemCount, InheritedAcl
    #' @param tenant_id (optional) Optional parameter to see shared data in another tenant
    #' @param volume_configuration_name (optional) Unique name of the volume configuration
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (VolumeListResponse) with additional information such as HTTP status code, headers
    #' @export
    ListVolumesWithHttpInfo = function(page_size = NULL, page_token = NULL, include = NULL, tenant_id = NULL, volume_configuration_name = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (`page_size` > 1000) {
        rlang::abort(message = "Invalid value for `page_size` when calling VolumesApi$ListVolumes, must be smaller than or equal to 1000.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid value for `page_size` when calling VolumesApi$ListVolumes, must be smaller than or equal to 1000."))
      }
      if (`page_size` < 0) {
        rlang::abort(message = "Invalid value for `page_size` when calling VolumesApi$ListVolumes, must be bigger than or equal to 0.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Invalid value for `page_size` when calling VolumesApi$ListVolumes, must be bigger than or equal to 0."))
      }





      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      query_params[["include"]] <- `include`

      query_params[["tenantId"]] <- `tenant_id`

      query_params[["volumeConfigurationName"]] <- `volume_configuration_name`

      local_var_url_path <- "/v1/volumes"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "VolumeListResponse", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Update a volume content
    #'
    #' @description
    #' Update a volume content
    #'
    #' @param volume_id Unique identifier for the volume to be updated.
    #' @param include (optional) Optionally include additional fields in the response.              Possible values: ObjectStoreAccess
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return VolumeResponse
    #' @export
    UpdateVolume = function(volume_id, include = NULL, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$UpdateVolumeWithHttpInfo(volume_id, include, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Update a volume content
    #'
    #' @description
    #' Update a volume content
    #'
    #' @param volume_id Unique identifier for the volume to be updated.
    #' @param include (optional) Optionally include additional fields in the response.              Possible values: ObjectStoreAccess
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (VolumeResponse) with additional information such as HTTP status code, headers
    #' @export
    UpdateVolumeWithHttpInfo = function(volume_id, include = NULL, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`volume_id`)) {
        rlang::abort(message = "Missing required parameter `volume_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `volume_id`."))
      }




      query_params[["include"]] <- `include`

      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/volumes/{volumeId}"
      if (!missing(`volume_id`)) {
        local_var_url_path <- gsub("\\{volumeId\\}", URLencode(as.character(`volume_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json-patch+json", "application/json", "text/json", "application/*+json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "VolumeResponse", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
