#' Workflow Execution Service
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Workflows operations
#' @description WorkflowsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateWorkflow } \emph{ Create a workflow }
#' Creates a new workflow and version (if provided).
#'
#' \itemize{
#' \item \emph{ @param } body \link{CreateWorkflowRequest}
#' \item \emph{ @returnType } \link{Workflow} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 201 | Details of the newly created workflow.
#'
#' \item return type : Workflow
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | A conflict was found. Ensure the workflow name is unique.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetWorkflow } \emph{ Get the details of a workflow }
#' Gets the details of a workflow with a given ID.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @returnType } \link{Workflow} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Details of the workflow.
#'
#' \item return type : Workflow
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListWorkflows } \emph{ Get a list of workflows }
#' Gets a list of workflows.
#'
#' \itemize{
#' \item \emph{ @param } tenant_id character
#' \item \emph{ @param } name character
#' \item \emph{ @param } categories list( character )
#' \item \emph{ @param } include list( character )
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @param } sort character
#' \item \emph{ @returnType } \link{WorkflowList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Paged list of workflows.
#'
#' \item return type : WorkflowList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateWorkflow } \emph{ Update an existing workflow }
#' Updates the workflow with a given ID.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } body \link{UpdateWorkflowRequest}
#' \item \emph{ @returnType } \link{Workflow} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Returns updated workflow.
#'
#' \item return type : Workflow
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | A conflict was found. Ensure the workflow name is unique.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateWorkflow  ####################
#'
#' library(icar1)
#' var_body <- CreateWorkflowRequest$new("name_example", "description_example", "organization_example", CreateWorkflowVersionRequest$new("version_example", "description_example", WorkflowLanguage$new("name_example", "version_example"), 123, c("acl_example"), "status_example"), "toolClass_example", c("acl_example"), c("categories_example")) # CreateWorkflowRequest |  (Optional)
#'
#' #Create a workflow
#' api_instance <- WorkflowsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  GetWorkflow  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#'
#' #Get the details of a workflow
#' api_instance <- WorkflowsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListWorkflows  ####################
#'
#' library(icar1)
#' var_tenant_id <- "tenant_id_example" # character | ID of the tenant (Optional)
#' var_name <- "name_example" # character |  (Optional)
#' var_categories <- c("inner_example") # array[character] |  (Optional)
#' var_include <- c("inner_example") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_page_size <- 10 # integer | Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (Optional)
#' var_page_token <- "page_token_example" # character | Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (Optional)
#' var_sort <- "timeCreated asc" # character | Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (Optional)
#'
#' #Get a list of workflows
#' api_instance <- WorkflowsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  UpdateWorkflow  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_body <- UpdateWorkflowRequest$new("name_example", "description_example", "organization_example", c("acl_example"), c("categories_example")) # UpdateWorkflowRequest |  (Optional)
#'
#' #Update an existing workflow
#' api_instance <- WorkflowsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
WorkflowsApi <- R6::R6Class(
  "WorkflowsApi",
  public = list(
    api_client = NULL,
    #' Initialize a new WorkflowsApi.
    #'
    #' @description
    #' Initialize a new WorkflowsApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Create a workflow
    #'
    #' @description
    #' Create a workflow
    #'
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Workflow
    #' @export
    CreateWorkflow = function(body = NULL, data_file = NULL, ...) {
      local_var_response <- self$CreateWorkflowWithHttpInfo(body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Create a workflow
    #'
    #' @description
    #' Create a workflow
    #'
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Workflow) with additional information such as HTTP status code, headers
    #' @export
    CreateWorkflowWithHttpInfo = function(body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE


      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Workflow", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get the details of a workflow
    #'
    #' @description
    #' Get the details of a workflow
    #'
    #' @param workflow_id ID of the workflow
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Workflow
    #' @export
    GetWorkflow = function(workflow_id, data_file = NULL, ...) {
      local_var_response <- self$GetWorkflowWithHttpInfo(workflow_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get the details of a workflow
    #'
    #' @description
    #' Get the details of a workflow
    #'
    #' @param workflow_id ID of the workflow
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Workflow) with additional information such as HTTP status code, headers
    #' @export
    GetWorkflowWithHttpInfo = function(workflow_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }


      local_var_url_path <- "/v1/workflows/{workflowId}"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Workflow", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of workflows
    #'
    #' @description
    #' Get a list of workflows
    #'
    #' @param tenant_id (optional) ID of the tenant
    #' @param name (optional) No description
    #' @param categories (optional) No description
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowList
    #' @export
    ListWorkflows = function(tenant_id = NULL, name = NULL, categories = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      local_var_response <- self$ListWorkflowsWithHttpInfo(tenant_id, name, categories, include, page_size, page_token, sort, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of workflows
    #'
    #' @description
    #' Get a list of workflows
    #'
    #' @param tenant_id (optional) ID of the tenant
    #' @param name (optional) No description
    #' @param categories (optional) No description
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowList) with additional information such as HTTP status code, headers
    #' @export
    ListWorkflowsWithHttpInfo = function(tenant_id = NULL, name = NULL, categories = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE








      query_params[["tenantId"]] <- `tenant_id`

      query_params[["name"]] <- `name`

      # no explore
      query_params[["categories"]] <- I(paste(lapply(`categories`, URLencode, reserved = TRUE), collapse = ","))

      # no explore
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      query_params[["sort"]] <- `sort`

      local_var_url_path <- "/v1/workflows"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Update an existing workflow
    #'
    #' @description
    #' Update an existing workflow
    #'
    #' @param workflow_id ID of the workflow
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return Workflow
    #' @export
    UpdateWorkflow = function(workflow_id, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$UpdateWorkflowWithHttpInfo(workflow_id, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Update an existing workflow
    #'
    #' @description
    #' Update an existing workflow
    #'
    #' @param workflow_id ID of the workflow
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (Workflow) with additional information such as HTTP status code, headers
    #' @export
    UpdateWorkflowWithHttpInfo = function(workflow_id, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }



      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows/{workflowId}"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "Workflow", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
