#' Workflow Execution Service
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title WorkflowVersions operations
#' @description WorkflowVersionsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ CreateWorkflowVersion } \emph{ Create a new workflow version }
#' Creates a new workflow version with a given workflow ID.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } body \link{CreateWorkflowVersionRequest}
#' \item \emph{ @returnType } \link{WorkflowVersion} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 201 | Details of the created workflow version.
#'
#' \item return type : WorkflowVersion
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | A conflict was found. Ensure the workflow version name is unique.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetWorkflowVersion } \emph{ Get the details of a workflow version }
#' Gets the details for a workflow version with a given workflow ID and version name.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } version_name character
#' \item \emph{ @returnType } \link{WorkflowVersion} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Details of the workflow version.
#'
#' \item return type : WorkflowVersion
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow ID or version name was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ LaunchWorkflowVersion } \emph{ Launch a workflow version }
#' Launches a workflow version with a given workflow ID and version name.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } version_name character
#' \item \emph{ @param } include Enum < [definition, engineParameters] >
#' \item \emph{ @param } body \link{LaunchWorkflowVersionRequest}
#' \item \emph{ @returnType } \link{WorkflowRun} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 201 | Details of the created workflow run.
#'
#' \item return type : WorkflowRun
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListAllWorkflowVersions } \emph{ Get a list of all workflow versions }
#' Gets a list of workflow versions across all workflows.
#'
#' \itemize{
#' \item \emph{ @param } tenant_id character
#' \item \emph{ @param } include Enum < [totalItemCount] >
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @param } sort character
#' \item \emph{ @returnType } \link{WorkflowVersionList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Paged list of workflow versions across all workflows.
#'
#' \item return type : WorkflowVersionList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListWorkflowVersions } \emph{ Get a list of workflow versions }
#' Gets a list of workflow versions with a given workflow ID.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } include Enum < [totalItemCount] >
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @param } sort character
#' \item \emph{ @returnType } \link{WorkflowVersionList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Paged list of workflow versions that the user has access to.
#'
#' \item return type : WorkflowVersionList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateWorkflowVersion } \emph{ Update an existing workflow version }
#' Updates an existing workflow version. Note: The Version, Definition, and Status cannot be changed simultaneously. Only one of these can be changed per API call.
#'
#' \itemize{
#' \item \emph{ @param } workflow_id character
#' \item \emph{ @param } version_name character
#' \item \emph{ @param } body \link{UpdateWorkflowVersionRequest}
#' \item \emph{ @returnType } \link{WorkflowVersion} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Details of the created workflow run.
#'
#' \item return type : WorkflowVersion
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 409 | A conflict was found. Ensure the workflow version name is unique.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow ID or version name was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  CreateWorkflowVersion  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_body <- CreateWorkflowVersionRequest$new("version_example", "description_example", WorkflowLanguage$new("name_example", "version_example"), 123, c("acl_example"), "draft") # CreateWorkflowVersionRequest |  (Optional)
#'
#' #Create a new workflow version
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  GetWorkflowVersion  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_version_name <- "version_name_example" # character | Name of the workflow version
#'
#' #Get the details of a workflow version
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  LaunchWorkflowVersion  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_version_name <- "version_name_example" # character | Name of the workflow version
#' var_include <- c("definition") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_body <- LaunchWorkflowVersionRequest$new("name_example", 123, 123) # LaunchWorkflowVersionRequest |  (Optional)
#'
#' #Launch a workflow version
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListAllWorkflowVersions  ####################
#'
#' library(icar1)
#' var_tenant_id <- "tenant_id_example" # character | ID of the tenant (Optional)
#' var_include <- c("totalItemCount") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_page_size <- 10 # integer | Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (Optional)
#' var_page_token <- "page_token_example" # character | Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (Optional)
#' var_sort <- "timeCreated asc" # character | Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (Optional)
#'
#' #Get a list of all workflow versions
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListWorkflowVersions  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_include <- c("totalItemCount") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_page_size <- 10 # integer | Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (Optional)
#' var_page_token <- "page_token_example" # character | Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (Optional)
#' var_sort <- "timeCreated asc" # character | Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (Optional)
#'
#' #Get a list of workflow versions
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  UpdateWorkflowVersion  ####################
#'
#' library(icar1)
#' var_workflow_id <- "workflow_id_example" # character | ID of the workflow
#' var_version_name <- "version_name_example" # character | Name of the workflow version
#' var_body <- UpdateWorkflowVersionRequest$new("version_example", "description_example", WorkflowLanguage$new("name_example", "version_example"), 123, c("acl_example"), "draft") # UpdateWorkflowVersionRequest |  (Optional)
#'
#' #Update an existing workflow version
#' api_instance <- WorkflowVersionsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
WorkflowVersionsApi <- R6::R6Class(
  "WorkflowVersionsApi",
  public = list(
    api_client = NULL,
    #' Initialize a new WorkflowVersionsApi.
    #'
    #' @description
    #' Initialize a new WorkflowVersionsApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Create a new workflow version
    #'
    #' @description
    #' Create a new workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowVersion
    #' @export
    CreateWorkflowVersion = function(workflow_id, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$CreateWorkflowVersionWithHttpInfo(workflow_id, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Create a new workflow version
    #'
    #' @description
    #' Create a new workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowVersion) with additional information such as HTTP status code, headers
    #' @export
    CreateWorkflowVersionWithHttpInfo = function(workflow_id, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }



      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows/{workflowId}/versions"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowVersion", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get the details of a workflow version
    #'
    #' @description
    #' Get the details of a workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowVersion
    #' @export
    GetWorkflowVersion = function(workflow_id, version_name, data_file = NULL, ...) {
      local_var_response <- self$GetWorkflowVersionWithHttpInfo(workflow_id, version_name, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get the details of a workflow version
    #'
    #' @description
    #' Get the details of a workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowVersion) with additional information such as HTTP status code, headers
    #' @export
    GetWorkflowVersionWithHttpInfo = function(workflow_id, version_name, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }

      if (missing(`version_name`)) {
        rlang::abort(message = "Missing required parameter `version_name`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `version_name`."))
      }



      local_var_url_path <- "/v1/workflows/{workflowId}/versions/{versionName}"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`version_name`)) {
        local_var_url_path <- gsub("\\{versionName\\}", URLencode(as.character(`version_name`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowVersion", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Launch a workflow version
    #'
    #' @description
    #' Launch a workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowRun
    #' @export
    LaunchWorkflowVersion = function(workflow_id, version_name, include = NULL, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$LaunchWorkflowVersionWithHttpInfo(workflow_id, version_name, include, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Launch a workflow version
    #'
    #' @description
    #' Launch a workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowRun) with additional information such as HTTP status code, headers
    #' @export
    LaunchWorkflowVersionWithHttpInfo = function(workflow_id, version_name, include = NULL, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }

      if (missing(`version_name`)) {
        rlang::abort(message = "Missing required parameter `version_name`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `version_name`."))
      }





      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("definition", "engineParameters"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowVersionsApi$LaunchWorkflowVersion. Must be [definition, engineParameters].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowVersionsApi$LaunchWorkflowVersion. Must be [definition, engineParameters]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows/{workflowId}/versions/{versionName}:launch"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`version_name`)) {
        local_var_url_path <- gsub("\\{versionName\\}", URLencode(as.character(`version_name`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowRun", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of all workflow versions
    #'
    #' @description
    #' Get a list of all workflow versions
    #'
    #' @param tenant_id (optional) ID of the tenant
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowVersionList
    #' @export
    ListAllWorkflowVersions = function(tenant_id = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      local_var_response <- self$ListAllWorkflowVersionsWithHttpInfo(tenant_id, include, page_size, page_token, sort, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of all workflow versions
    #'
    #' @description
    #' Get a list of all workflow versions
    #'
    #' @param tenant_id (optional) ID of the tenant
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowVersionList) with additional information such as HTTP status code, headers
    #' @export
    ListAllWorkflowVersionsWithHttpInfo = function(tenant_id = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE






      query_params[["tenantId"]] <- `tenant_id`

      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("totalItemCount"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowVersionsApi$ListAllWorkflowVersions. Must be [totalItemCount].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowVersionsApi$ListAllWorkflowVersions. Must be [totalItemCount]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      query_params[["sort"]] <- `sort`

      local_var_url_path <- "/v1/workflows/versions"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowVersionList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of workflow versions
    #'
    #' @description
    #' Get a list of workflow versions
    #'
    #' @param workflow_id ID of the workflow
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowVersionList
    #' @export
    ListWorkflowVersions = function(workflow_id, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      local_var_response <- self$ListWorkflowVersionsWithHttpInfo(workflow_id, include, page_size, page_token, sort, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of workflow versions
    #'
    #' @description
    #' Get a list of workflow versions
    #'
    #' @param workflow_id ID of the workflow
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowVersionList) with additional information such as HTTP status code, headers
    #' @export
    ListWorkflowVersionsWithHttpInfo = function(workflow_id, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }






      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("totalItemCount"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowVersionsApi$ListWorkflowVersions. Must be [totalItemCount].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowVersionsApi$ListWorkflowVersions. Must be [totalItemCount]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      query_params[["sort"]] <- `sort`

      local_var_url_path <- "/v1/workflows/{workflowId}/versions"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowVersionList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Update an existing workflow version
    #'
    #' @description
    #' Update an existing workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowVersion
    #' @export
    UpdateWorkflowVersion = function(workflow_id, version_name, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$UpdateWorkflowVersionWithHttpInfo(workflow_id, version_name, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Update an existing workflow version
    #'
    #' @description
    #' Update an existing workflow version
    #'
    #' @param workflow_id ID of the workflow
    #' @param version_name Name of the workflow version
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowVersion) with additional information such as HTTP status code, headers
    #' @export
    UpdateWorkflowVersionWithHttpInfo = function(workflow_id, version_name, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`workflow_id`)) {
        rlang::abort(message = "Missing required parameter `workflow_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `workflow_id`."))
      }

      if (missing(`version_name`)) {
        rlang::abort(message = "Missing required parameter `version_name`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `version_name`."))
      }




      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows/{workflowId}/versions/{versionName}"
      if (!missing(`workflow_id`)) {
        local_var_url_path <- gsub("\\{workflowId\\}", URLencode(as.character(`workflow_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`version_name`)) {
        local_var_url_path <- gsub("\\{versionName\\}", URLencode(as.character(`version_name`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json-patch+json", "application/json", "text/json", "application/*+json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PATCH",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowVersion", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
