#' Workflow Execution Service
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title WorkflowRuns operations
#' @description WorkflowRunsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ AbortWorkflowRun } \emph{ Abort a workflow run }
#' Aborts the workflow run with a given ID.
#'
#' \itemize{
#' \item \emph{ @param } run_id character
#' \item \emph{ @param } include Enum < [definition, engineParameters] >
#' \item \emph{ @param } body \link{AbortWorkflowRunRequest}
#' \item \emph{ @returnType } \link{WorkflowRun} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Details of the aborted workflow run.
#'
#' \item return type : WorkflowRun
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow run with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetWorkflowRun } \emph{ Get the details of a workflow run }
#' Gets the details of a workflow run with a given ID.
#'
#' \itemize{
#' \item \emph{ @param } run_id character
#' \item \emph{ @param } include Enum < [definition, engineParameters] >
#' \item \emph{ @returnType } \link{WorkflowRun} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Details of the workflow run.
#'
#' \item return type : WorkflowRun
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow run with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListWorkflowRunHistory } \emph{ Get a list of workflow run history events }
#' Gets a list of history events for a workflow run with a given ID.
#'
#' \itemize{
#' \item \emph{ @param } run_id character
#' \item \emph{ @param } sort character
#' \item \emph{ @param } include Enum < [totalItemCount] >
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @returnType } \link{WorkflowRunHistoryEventList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Paged list of workflow run history events.
#'
#' \item return type : WorkflowRunHistoryEventList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | The workflow run with the specified ID was not found.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListWorkflowRuns } \emph{ Get a list of workflow runs }
#' Gets a list of workflow runs.
#'
#' \itemize{
#' \item \emph{ @param } status Enum < [aborted, aborting, failed, new, running, submitted, succeeded, timedOut] >
#' \item \emph{ @param } tenant_id character
#' \item \emph{ @param } name character
#' \item \emph{ @param } include Enum < [totalItemCount] >
#' \item \emph{ @param } page_size integer
#' \item \emph{ @param } page_token character
#' \item \emph{ @param } sort character
#' \item \emph{ @returnType } \link{WorkflowRunList} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Paged list of workflow runs that the user has access to.
#'
#' \item return type : WorkflowRunList
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 400 | Invalid request.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 401 | Unauthorized
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 403 | Permission denied.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | Unexpected issue. Please try your request again. If problem persists, please contact the system administrator.
#'
#' \item return type : ErrorResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  AbortWorkflowRun  ####################
#'
#' library(icar1)
#' var_run_id <- "run_id_example" # character | ID of the workflow run
#' var_include <- c("definition") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_body <- AbortWorkflowRunRequest$new("error_example", "cause_example") # AbortWorkflowRunRequest |  (Optional)
#'
#' #Abort a workflow run
#' api_instance <- WorkflowRunsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  GetWorkflowRun  ####################
#'
#' library(icar1)
#' var_run_id <- "run_id_example" # character | ID of the workflow run
#' var_include <- c("definition") # array[character] | Comma-separated list of properties to include in the response (Optional)
#'
#' #Get the details of a workflow run
#' api_instance <- WorkflowRunsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListWorkflowRunHistory  ####################
#'
#' library(icar1)
#' var_run_id <- "run_id_example" # character | ID of the workflow run
#' var_sort <- "eventId asc" # character |  (Optional)
#' var_include <- c("totalItemCount") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_page_size <- 10 # integer | Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (Optional)
#' var_page_token <- "page_token_example" # character | Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (Optional)
#'
#' #Get a list of workflow run history events
#' api_instance <- WorkflowRunsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' ####################  ListWorkflowRuns  ####################
#'
#' library(icar1)
#' var_status <- c("aborted") # array[character] |  (Optional)
#' var_tenant_id <- "tenant_id_example" # character | ID of the tenant (Optional)
#' var_name <- "name_example" # character |  (Optional)
#' var_include <- c("totalItemCount") # array[character] | Comma-separated list of properties to include in the response (Optional)
#' var_page_size <- 10 # integer | Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (Optional)
#' var_page_token <- "page_token_example" # character | Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified. (Optional)
#' var_sort <- "timeCreated asc" # character | Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (Optional)
#'
#' #Get a list of workflow runs
#' api_instance <- WorkflowRunsApi$new()
#'
#' # Configure API key authorization: Bearer
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
WorkflowRunsApi <- R6::R6Class(
  "WorkflowRunsApi",
  public = list(
    api_client = NULL,
    #' Initialize a new WorkflowRunsApi.
    #'
    #' @description
    #' Initialize a new WorkflowRunsApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Abort a workflow run
    #'
    #' @description
    #' Abort a workflow run
    #'
    #' @param run_id ID of the workflow run
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowRun
    #' @export
    AbortWorkflowRun = function(run_id, include = NULL, body = NULL, data_file = NULL, ...) {
      local_var_response <- self$AbortWorkflowRunWithHttpInfo(run_id, include, body, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Abort a workflow run
    #'
    #' @description
    #' Abort a workflow run
    #'
    #' @param run_id ID of the workflow run
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param body (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowRun) with additional information such as HTTP status code, headers
    #' @export
    AbortWorkflowRunWithHttpInfo = function(run_id, include = NULL, body = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`run_id`)) {
        rlang::abort(message = "Missing required parameter `run_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `run_id`."))
      }




      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("definition", "engineParameters"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowRunsApi$AbortWorkflowRun. Must be [definition, engineParameters].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowRunsApi$AbortWorkflowRun. Must be [definition, engineParameters]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      if (!is.null(`body`)) {
        local_var_body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/v1/workflows/runs/{runId}:abort"
      if (!missing(`run_id`)) {
        local_var_url_path <- gsub("\\{runId\\}", URLencode(as.character(`run_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json-patch+json", "application/json", "text/json", "application/*+json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PUT",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowRun", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get the details of a workflow run
    #'
    #' @description
    #' Get the details of a workflow run
    #'
    #' @param run_id ID of the workflow run
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowRun
    #' @export
    GetWorkflowRun = function(run_id, include = NULL, data_file = NULL, ...) {
      local_var_response <- self$GetWorkflowRunWithHttpInfo(run_id, include, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get the details of a workflow run
    #'
    #' @description
    #' Get the details of a workflow run
    #'
    #' @param run_id ID of the workflow run
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowRun) with additional information such as HTTP status code, headers
    #' @export
    GetWorkflowRunWithHttpInfo = function(run_id, include = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`run_id`)) {
        rlang::abort(message = "Missing required parameter `run_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `run_id`."))
      }



      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("definition", "engineParameters"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowRunsApi$GetWorkflowRun. Must be [definition, engineParameters].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowRunsApi$GetWorkflowRun. Must be [definition, engineParameters]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      local_var_url_path <- "/v1/workflows/runs/{runId}"
      if (!missing(`run_id`)) {
        local_var_url_path <- gsub("\\{runId\\}", URLencode(as.character(`run_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowRun", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of workflow run history events
    #'
    #' @description
    #' Get a list of workflow run history events
    #'
    #' @param run_id ID of the workflow run
    #' @param sort (optional) No description (default value: "eventId asc")
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowRunHistoryEventList
    #' @export
    ListWorkflowRunHistory = function(run_id, sort = "eventId asc", include = NULL, page_size = 10, page_token = NULL, data_file = NULL, ...) {
      local_var_response <- self$ListWorkflowRunHistoryWithHttpInfo(run_id, sort, include, page_size, page_token, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of workflow run history events
    #'
    #' @description
    #' Get a list of workflow run history events
    #'
    #' @param run_id ID of the workflow run
    #' @param sort (optional) No description (default value: "eventId asc")
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowRunHistoryEventList) with additional information such as HTTP status code, headers
    #' @export
    ListWorkflowRunHistoryWithHttpInfo = function(run_id, sort = "eventId asc", include = NULL, page_size = 10, page_token = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`run_id`)) {
        rlang::abort(message = "Missing required parameter `run_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `run_id`."))
      }






      query_params[["sort"]] <- `sort`

      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("totalItemCount"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowRunsApi$ListWorkflowRunHistory. Must be [totalItemCount].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowRunsApi$ListWorkflowRunHistory. Must be [totalItemCount]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      local_var_url_path <- "/v1/workflows/runs/{runId}/history"
      if (!missing(`run_id`)) {
        local_var_url_path <- gsub("\\{runId\\}", URLencode(as.character(`run_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowRunHistoryEventList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get a list of workflow runs
    #'
    #' @description
    #' Get a list of workflow runs
    #'
    #' @param status (optional) No description
    #' @param tenant_id (optional) ID of the tenant
    #' @param name (optional) No description
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return WorkflowRunList
    #' @export
    ListWorkflowRuns = function(status = NULL, tenant_id = NULL, name = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      local_var_response <- self$ListWorkflowRunsWithHttpInfo(status, tenant_id, name, include, page_size, page_token, sort, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get a list of workflow runs
    #'
    #' @description
    #' Get a list of workflow runs
    #'
    #' @param status (optional) No description
    #' @param tenant_id (optional) ID of the tenant
    #' @param name (optional) No description
    #' @param include (optional) Comma-separated list of properties to include in the response
    #' @param page_size (optional) Number of items to include in a page. Value must be an integer between 1 and 1000. Only one of pageSize or pageToken can be specified. (default value: 10)
    #' @param page_token (optional) Page offset descriptor. Valid page tokens are included in the response. Only one of pageSize or pageToken can be specified.
    #' @param sort (optional) Specifies the order to include list items as \"_{fieldName}_ [asc|desc]\". The second field is optional and specifies the sort direction (\"asc\" for ascending or \"desc\" for descending). (default value: "timeCreated asc")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (WorkflowRunList) with additional information such as HTTP status code, headers
    #' @export
    ListWorkflowRunsWithHttpInfo = function(status = NULL, tenant_id = NULL, name = NULL, include = NULL, page_size = 10, page_token = NULL, sort = "timeCreated asc", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE








      # no explore
      # validate enum values
      for (query_item in `status`) {
        if (!(query_item %in% c("aborted", "aborting", "failed", "new", "running", "submitted", "succeeded", "timedOut"))) {
          rlang::abort(message = "Invalid value for `status` when calling WorkflowRunsApi$ListWorkflowRuns. Must be [aborted, aborting, failed, new, running, submitted, succeeded, timedOut].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `status` when calling WorkflowRunsApi$ListWorkflowRuns. Must be [aborted, aborting, failed, new, running, submitted, succeeded, timedOut]."))
        }
      }
      query_params[["status"]] <- I(paste(lapply(`status`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["tenantId"]] <- `tenant_id`

      query_params[["name"]] <- `name`

      # no explore
      # validate enum values
      for (query_item in `include`) {
        if (!(query_item %in% c("totalItemCount"))) {
          rlang::abort(message = "Invalid value for `include` when calling WorkflowRunsApi$ListWorkflowRuns. Must be [totalItemCount].",
                       .subclass = "ApiException",
                       ApiException = ApiException$new(status = 0,
                                                       reason = "Invalid value for `include` when calling WorkflowRunsApi$ListWorkflowRuns. Must be [totalItemCount]."))
        }
      }
      query_params[["include"]] <- I(paste(lapply(`include`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["pageSize"]] <- `page_size`

      query_params[["pageToken"]] <- `page_token`

      query_params[["sort"]] <- `sort`

      local_var_url_path <- "/v1/workflows/runs"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "WorkflowRunList", loadNamespace("icar1")),
          error = function(e) {
            rlang::abort(message = "Failed to deserialize response",
                         .subclass = "ApiException",
                         ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
